DO-AN-02: AppESPWrap/AppESPWrap.c File Reference
AppESPWrap.c File Reference
#include "All.h"
Functions
void IOConfig (uint64_t pin_bit_mask, gpio_mode_t mode, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en, gpio_int_type_t intr_type)
Configure a GPIO pin with specific mode, pull-up/down settings, and interrupt type.
void IOConfigAsOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as output with no internal pull resistors and interrupts disabled.
void IOConfigAsInput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as input with no internal pull resistors and interrupts disabled.
void IOConfigAsOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Output Open-Drain with Internal Pull-up enabled.
void IOConfigAsInputOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO as Input and Output (Bidirectional)
void IOConfigAsInputOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Input/Output Open-Drain with Internal Pull-up.
Function Documentation
IOConfig()
void IOConfig (uint64_t pin_bit_mask, gpio_mode_t mode, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en, gpio_int_type_t intr_type)
Configure a GPIO pin with specific mode, pull-up/down settings, and interrupt type.
Parameters
pin_bit_mask Bitmask of the GPIO(s) to configure
mode GPIO mode (e.g., GPIO_MODE_INPUT, GPIO_MODE_OUTPUT)
pull_up_en Enable/Disable pull-up resistor
pull_down_en Enable/Disable pull-down resistor
intr_type Interrupt type (e.g., GPIO_INTR_POSEDGE, GPIO_INTR_DISABLE)
Definition at line 3 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    if(intr_type <= 0)           intr_type      = GPIO_INTR_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = mode,
        .intr_type = intr_type,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
IOConfigAsInput()
void IOConfigAsInput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as input with no internal pull resistors and interrupts disabled.
Parameters
pin_bit_mask Bitmask of the GPIO(s) to configure
Definition at line 30 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_INPUT,
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
Referenced by LCD32FlushCanvasFast(), P16ComInit(), P16ComRead(), P16ComReadArray(), P16ComWrite(), and P16ComWriteArray().
IOConfigAsInputOutput()
void IOConfigAsInputOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO as Input and Output (Bidirectional)
Parameters
pin_bit_mask Bit mask of the pin
pull_up_en Enable internal pull-up
pull_down_en Enable internal pull-down
Definition at line 54 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_INPUT_OUTPUT,     // Input + Output
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
IOConfigAsInputOutputODPullUp()
void IOConfigAsInputOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Input/Output Open-Drain with Internal Pull-up.
Parameters
pin_bit_mask Bit mask of the pin
Definition at line 68 of file AppESPWrap.c.
{
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_INPUT_OUTPUT_OD,  // Input + Output Open-Drain
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = GPIO_PULLUP_ENABLE,   // Force Enable Pull-up
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
    };
    gpio_config(&pin);
}
IOConfigAsOutput()
void IOConfigAsOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as output with no internal pull resistors and interrupts disabled.
Parameters
pin_bit_mask Bitmask of the GPIO(s) to configure
Definition at line 17 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_OUTPUT,
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
Referenced by LCD32FlushCanvasFast(), LCD32Init(), P16ComInit(), P16ComRead(), P16ComReadArray(), P16ComWrite(), and P16ComWriteArray().
IOConfigAsOutputODPullUp()
void IOConfigAsOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Output Open-Drain with Internal Pull-up enabled.
Parameters
pin_bit_mask Bit mask of the pin
Definition at line 43 of file AppESPWrap.c.
{
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_OUTPUT_OD,        // Output Open-Drain
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = GPIO_PULLUP_ENABLE,   // Force Enable Pull-up
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
    };
    gpio_config(&pin);
}