DO-AN-02: AppESPWrap/ESPGPIOWrapper.h File Reference
ESPGPIOWrapper.h File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdarg.h>
#include "driver/gpio.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "rom/ets_sys.h"
#include "hal/gpio_ll.h"
#include "soc/gpio_struct.h"
#include "soc/gpio_reg.h"
Macros
#define IOStandardGet()
High-resolution timer API.
#define IOExtendedGet()
Get input level of all GPIO 32-39+ (Atomic, Fast)
#define IOStandardSet(mask)
Set output level High for GPIO 0-31 (Atomic, Fast)
#define IOStandardClr(mask)
Set output level Low for GPIO 0-31 (Atomic, Fast)
#define IOExtendedSet(mask)
Set output level High for GPIO 32-39+ (Atomic, Fast)
#define IOExtendedClr(mask)
Set output level Low for GPIO 32-39+ (Atomic, Fast)
#define IOGet()
Get input level of ALL GPIOs (0-39+) combined.
#define IOSet(mask64)
Set output level High for ANY GPIOs (0-39+)
#define IOClr(mask64)
Set output level Low for ANY GPIOs (0-39+)
#define GPIOSetHigh(GPIO_MASK)
Fast set High for GPIO 0-31 (Write 1 to Set)
#define GPIOSetLow(GPIO_MASK)
Fast set Low for GPIO 0-31 (Write 1 to Clear)
#define GPIOSetHigh1(GPIO_MASK)
Fast set High for GPIO 32-64 (Write 1 to Set - High Register)
#define GPIOSetLow1(GPIO_MASK)
Fast set Low for GPIO 32-64 (Write 1 to Clear - High Register)
Functions
void IOConfig (uint64_t pin_bit_mask, gpio_mode_t mode, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en, gpio_int_type_t intr_type)
Configure a GPIO pin with specific mode, pull-up/down settings, and interrupt type.
void IOConfigAsOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as output with no internal pull resistors and interrupts disabled.
void IOConfigAsInput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as input with no internal pull resistors and interrupts disabled.
void IOConfigAsInputOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Input/Output Open-Drain with Internal Pull-up.
void IOConfigAsInputOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO as Input and Output (Bidirectional)
void IOConfigAsOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Output Open-Drain with Internal Pull-up enabled.
Macro Definition Documentation
GPIOSetHigh
#define GPIOSetHigh (GPIO_MASK)
Value:
GPIO.out_w1ts = (GPIO_MASK)
Fast set High for GPIO 0-31 (Write 1 to Set)
Definition at line 104 of file ESPGPIOWrapper.h.
GPIOSetHigh1
#define GPIOSetHigh1 (GPIO_MASK)
Value:
GPIO.out1_w1ts = (GPIO_MASK)
Fast set High for GPIO 32-64 (Write 1 to Set - High Register)
Definition at line 110 of file ESPGPIOWrapper.h.
GPIOSetLow
#define GPIOSetLow (GPIO_MASK)
Value:
GPIO.out_w1tc = (GPIO_MASK)
Fast set Low for GPIO 0-31 (Write 1 to Clear)
Definition at line 107 of file ESPGPIOWrapper.h.
GPIOSetLow1
#define GPIOSetLow1 (GPIO_MASK)
Value:
GPIO.out1_w1tc = (GPIO_MASK)
Fast set Low for GPIO 32-64 (Write 1 to Clear - High Register)
Definition at line 113 of file ESPGPIOWrapper.h.
IOClr
#define IOClr (mask64)
Value:
                                        do { \
                                        IOStandardClr((uint32_t)(mask64)); \
                                        IOExtendedClr((uint32_t)((uint64_t)(mask64) >> 32)); \
                                     } while(0)
Set output level Low for ANY GPIOs (0-39+)
Parameters
mask64 64-bit Bitmask of pins to clear (must use 1ULL << pin)
Definition at line 68 of file ESPGPIOWrapper.h.
#define IOClr(mask64)                do { \
                                        IOStandardClr((uint32_t)(mask64)); \
                                        IOExtendedClr((uint32_t)((uint64_t)(mask64) >> 32)); \
                                     } while(0)
Referenced by LCD32FlushCanvasFast(), P16ComWrite(), and P16ComWriteArray().
IOExtendedClr
#define IOExtendedClr (mask)
Value:
(GPIO.out1_w1tc.val = (uint32_t)(mask))
Set output level Low for GPIO 32-39+ (Atomic, Fast)
Parameters
mask Bitmask relative to the high bank
Definition at line 51 of file ESPGPIOWrapper.h.
IOExtendedGet
#define IOExtendedGet ()
Value:
(GPIO.in1.val)
Get input level of all GPIO 32-39+ (Atomic, Fast)
Returns
32-bit raw value (Bit N = GPIO 32+N status)
Definition at line 35 of file ESPGPIOWrapper.h.
IOExtendedSet
#define IOExtendedSet (mask)
Value:
(GPIO.out1_w1ts.val = (uint32_t)(mask))
Set output level High for GPIO 32-39+ (Atomic, Fast)
Parameters
mask Bitmask relative to the high bank (bit 0 = GPIO 32)
Definition at line 47 of file ESPGPIOWrapper.h.
IOGet
#define IOGet ()
Value:
(((uint64_t)IOExtendedGet() << 32) | (uint64_t)IOStandardGet())
Get input level of ALL GPIOs (0-39+) combined.
Reads both low and high banks and combines them. Note: Not strictly atomic across banks (2 separate reads).
Returns
64-bit raw value (Bit N = GPIO N status)
Definition at line 57 of file ESPGPIOWrapper.h.
IOSet
#define IOSet (mask64)
Value:
                                        do { \
                                        IOStandardSet((uint32_t)(mask64)); \
                                        IOExtendedSet((uint32_t)((uint64_t)(mask64) >> 32)); \
                                     } while(0)
Set output level High for ANY GPIOs (0-39+)
Parameters
mask64 64-bit Bitmask of pins to set (must use 1ULL << pin)
Definition at line 61 of file ESPGPIOWrapper.h.
#define IOSet(mask64)                do { \
                                        IOStandardSet((uint32_t)(mask64)); \
                                        IOExtendedSet((uint32_t)((uint64_t)(mask64) >> 32)); \
                                     } while(0)
Referenced by LCD32FlushCanvasFast(), P16ComWrite(), and P16ComWriteArray().
IOStandardClr
#define IOStandardClr (mask)
Value:
(GPIO.out_w1tc = (uint32_t)(mask))
Set output level Low for GPIO 0-31 (Atomic, Fast)
Parameters
mask Bitmask of pins to clear
Definition at line 43 of file ESPGPIOWrapper.h.
IOStandardGet
#define IOStandardGet ()
Value:
(GPIO.in)
High-resolution timer API.
Standard fixed-width integer types Standard library definitions (malloc, free, etc.) Boolean type definitions Variable argument handling ESP-IDF High-level GPIO driver ESP logging utilities ROM functions (ets_printf, ets_delay_us) Low-level GPIO hardware abstraction layer GPIO hardware register structure GPIO register addresses and bit masks
Get input level of all GPIO 0-31 (Atomic, Fast)
Returns
32-bit raw value (Bit N = GPIO N status)
Definition at line 31 of file ESPGPIOWrapper.h.
Referenced by P16ComRead(), and P16ComReadArray().
IOStandardSet
#define IOStandardSet (mask)
Value:
(GPIO.out_w1ts = (uint32_t)(mask))
Set output level High for GPIO 0-31 (Atomic, Fast)
Parameters
mask Bitmask of pins to set (1 bit = 1 pin)
Definition at line 39 of file ESPGPIOWrapper.h.
Referenced by P16ComInit().
Function Documentation
IOConfig()
void IOConfig (uint64_t pin_bit_mask, gpio_mode_t mode, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en, gpio_int_type_t intr_type)
Configure a GPIO pin with specific mode, pull-up/down settings, and interrupt type.
Parameters
pin_bit_mask Bitmask of the GPIO(s) to configure
mode GPIO mode (e.g., GPIO_MODE_INPUT, GPIO_MODE_OUTPUT)
pull_up_en Enable/Disable pull-up resistor
pull_down_en Enable/Disable pull-down resistor
intr_type Interrupt type (e.g., GPIO_INTR_POSEDGE, GPIO_INTR_DISABLE)
Definition at line 3 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    if(intr_type <= 0)           intr_type      = GPIO_INTR_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = mode,
        .intr_type = intr_type,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
IOConfigAsInput()
void IOConfigAsInput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as input with no internal pull resistors and interrupts disabled.
Parameters
pin_bit_mask Bitmask of the GPIO(s) to configure
Definition at line 30 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_INPUT,
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
Referenced by LCD32FlushCanvasFast(), P16ComInit(), P16ComRead(), P16ComReadArray(), P16ComWrite(), and P16ComWriteArray().
IOConfigAsInputOutput()
void IOConfigAsInputOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO as Input and Output (Bidirectional)
Parameters
pin_bit_mask Bit mask of the pin
pull_up_en Enable internal pull-up
pull_down_en Enable internal pull-down
Definition at line 54 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_INPUT_OUTPUT,     // Input + Output
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
IOConfigAsInputOutputODPullUp()
void IOConfigAsInputOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Input/Output Open-Drain with Internal Pull-up.
Parameters
pin_bit_mask Bit mask of the pin
Definition at line 68 of file AppESPWrap.c.
{
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_INPUT_OUTPUT_OD,  // Input + Output Open-Drain
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = GPIO_PULLUP_ENABLE,   // Force Enable Pull-up
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
    };
    gpio_config(&pin);
}
IOConfigAsOutput()
void IOConfigAsOutput (uint64_t pin_bit_mask, gpio_pullup_t pull_up_en, gpio_pulldown_t pull_down_en)
Configure GPIO(s) as output with no internal pull resistors and interrupts disabled.
Parameters
pin_bit_mask Bitmask of the GPIO(s) to configure
Definition at line 17 of file AppESPWrap.c.
{
    if(pull_up_en <= 0)          pull_up_en     = GPIO_PULLUP_DISABLE;
    if(pull_down_en <= 0)        pull_down_en   = GPIO_PULLDOWN_DISABLE;
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_OUTPUT,
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = pull_up_en,
        .pull_down_en = pull_down_en,
    };
    gpio_config(&pin);
}
Referenced by LCD32FlushCanvasFast(), LCD32Init(), P16ComInit(), P16ComRead(), P16ComReadArray(), P16ComWrite(), and P16ComWriteArray().
IOConfigAsOutputODPullUp()
void IOConfigAsOutputODPullUp (uint64_t pin_bit_mask)
Configure GPIO as Output Open-Drain with Internal Pull-up enabled.
Parameters
pin_bit_mask Bit mask of the pin
Definition at line 43 of file AppESPWrap.c.
{
    gpio_config_t pin = {
        .pin_bit_mask = pin_bit_mask,
        .mode = GPIO_MODE_OUTPUT_OD,        // Output Open-Drain
        .intr_type = GPIO_INTR_DISABLE,
        .pull_up_en = GPIO_PULLUP_ENABLE,   // Force Enable Pull-up
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
    };
    gpio_config(&pin);
}