DO-AN-02: comDriver/i2c/i2c.h File Reference
i2c.h File Reference
#include "../../helper/general.h"
#include "i2cLog.h"
#include "i2cDefinition.h"
#include "i2cHelper.h"
Functions
<<<<<<< HEAD=======> > > > > > master<<<<<<< HEAD=======> static master void IRAM_ATTR i2cHandleSCLIsr (void *pvI2CDev)
Handle SCL interrupt in slave mode.
static void IRAM_ATTR i2cHandleSDAIsr (void *pvI2CDev)
Handle SDA interrupt in slave mode.
def createI2CDevice (i2cDev_t **pDev)
Create a new I2C device instance.
def configI2CDevice (i2cDev_t *dev, uint8_t addr, pin_t scl, pin_t sda, flag_t config)
Configure I2C device pins and options.
def startupI2CDevice (i2cDev_t *dev)
Startup the I2C device (initialize GPIO and configs)
def i2cSetTransmitBuffer (i2cDev_t *dev, void *tBuff, size_t size)
Set transmit buffer for I2C.
def i2cSetReceiveBuffer (i2cDev_t *dev, void *rBuff, size_t size)
Set receive buffer for I2C.
def i2cSendByte (i2cDev_t *dev, uint8_t addr7, uint8_t rw, uint8_t byte, flag_t extConf)
Send a specified byte.
def i2cSendDoubleByte (i2cDev_t *dev, uint8_t addr7, uint8_t rw, uint8_t byteHigh, uint8_t byteLow, flag_t extConf)
Send a specified double byte.
def i2cSendBuffer (i2cDev_t *dev, uint8_t addr7, uint8_t rw, flag_t extConf)
Send all bytes in the transmit buffer.
def i2cReceiveBuffer (i2cDev_t *dev, uint8_t addr7, uint8_t rw, flag_t extConf)
Receive all bytes in the transmit buffer.
def destroyI2CDevice (i2cDev_t *dev)
Deinitialize and free an I2C device.
Function Documentation
configI2CDevice()
def configI2CDevice (i2cDev_t * dev, uint8_t addr, pin_t scl, pin_t sda, flag_t config)
Configure I2C device pins and options.
Parameters
dev Pointer to i2cDev_t
addr Address of this device (for slave mode)
scl Pin number for SCL
sda Pin number for SDA
config Configuration flags. See I2C_CONFIG_ORDER enum.
Returns
Default return status
Set new proterties
Clear all ptr buffer!
Definition at line 36 of file i2c.c.
{
    __i2cEntry("configI2CDevice(dev: %p, SCL: %d, SDA: %d, config: 0x%04x)", dev, scl, sda, config);
    if(__is_null(dev)) {
        __i2cErr("dev is null!");
        __i2cExit("configI2CDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
    }
    dev->addr   = addr;
    dev->scl    = scl;
    dev->sda    = sda;
    dev->conf   = config;
    dev->freq   =   ((config & 0x3) == I2C_STANDARD_MODE)   ? (100000) :
                    ((config & 0x3) == I2C_FAST_MODE)       ? (400000) :
                    ((config & 0x3) == I2C_FAST_PLUS_MODE)  ? (800000) : (1000000);
    dev->txPtr = NULL;
    dev->txSize= 0;
    dev->txIndByte = 0;
    dev->txIndBit = 0;
    dev->rxPtr = NULL;
    dev->rxSize= 0;
    dev->rxIndBit = 0;
    dev->rxIndByte = 0;
    portMUX_TYPE mutex = portMUX_INITIALIZER_UNLOCKED;
    dev->mutex = mutex;
    __i2cExit("configI2CDevice() : %s", STR(OKE));
    return OKE;
}
References i2cDev_t::addr, i2cDev_t::conf, ERR_NULL, i2cDev_t::freq, I2C_FAST_MODE, I2C_FAST_PLUS_MODE, I2C_STANDARD_MODE, OKE, i2cDev_t::rxIndBit, i2cDev_t::rxIndByte, i2cDev_t::rxPtr, i2cDev_t::rxSize, i2cDev_t::scl, i2cDev_t::sda, i2cDev_t::txIndBit, i2cDev_t::txIndByte, i2cDev_t::txPtr, and i2cDev_t::txSize.
Referenced by configOLEDDevice().
createI2CDevice()
def createI2CDevice (i2cDev_t ** pDev)
Create a new I2C device instance.
Parameters
pDev Pointer to pointer of i2cDev_t (will store created device)
Returns
Default return status
Definition at line 12 of file i2c.c.
{
    __i2cEntry("createI2CDevice(i2cDev_t ** pDev)");
    if(__is_null(pDev)) {
        __i2cErr("pDev is null!");
        __i2cExit("createI2CDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
    }
    (*pDev) = NULL;
    (*pDev) = (i2cDev_t*) malloc(sizeof(i2cDev_t));
    if(__is_null(*pDev)){
        __i2cErr("Cannot allocate new i2cDev_t!");
        __i2cExit("createI2CDevice() : %s", STR(ERR_MALLOC_FAILED));
        return ERR_MALLOC_FAILED;
    }
    memset(*pDev, 0, sizeof(i2cDev_t));
    __i2cExit("createI2CDevice() : %s", STR(OKE));
    return OKE;
}
References ERR_MALLOC_FAILED, ERR_NULL, and OKE.
Referenced by createOLEDDevice().
destroyI2CDevice()
def destroyI2CDevice (i2cDev_t * dev)
Deinitialize and free an I2C device.
Parameters
dev Pointer to the I2C device structure.
Returns
OKE on success, ERR_NULL if dev is NULL.
Remove ISR handlers if installed (for slave mode)
Set pins to High-Z input (safe state)
Clear fields before freeing
Free device structure
Definition at line 410 of file i2c.c.
{
    __i2cEntry("destroyI2CDevice(%p)", dev);
    if(__is_null(dev)){
        __i2cErr("dev is null!");
        __i2cExit("destroyI2CDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
    }
    gpio_isr_handler_remove(dev->sda);
    gpio_isr_handler_remove(dev->scl);
    if(__isnot_negative(dev->sda)){
        gpio_config_t sdaHighZ = {
            .intr_type = GPIO_INTR_DISABLE,
            .mode = GPIO_MODE_INPUT,
            .pin_bit_mask = (1ULL << dev->sda),
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .pull_up_en = GPIO_PULLUP_DISABLE,
        };
        gpio_config(&sdaHighZ);
    }
    if(__isnot_negative(dev->scl)){
        gpio_config_t sclHighZ = {
            .intr_type = GPIO_INTR_DISABLE,
            .mode = GPIO_MODE_INPUT,
            .pin_bit_mask = (1ULL << dev->scl),
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .pull_up_en = GPIO_PULLUP_DISABLE,
        };
        gpio_config(&sclHighZ);
    }
    memset(dev, 0, sizeof(i2cDev_t));
    free(dev);
    __i2cExit("destroyI2CDevice() : %s", STR(OKE));
    return OKE;
}
References ERR_NULL, OKE, i2cDev_t::scl, and i2cDev_t::sda.
i2cHandleSCLIsr()
<<<<<<< HEAD======= > > > > > > master<<<<<<< HEAD=======> static master void IRAM_ATTR i2cHandleSCLIsr (void * pvI2CDev) static
Handle SCL interrupt in slave mode.
Parameters
pv Pointer to i2cDev_t
Definition at line 52 of file i2c.h.
{
    __i2cEntry("i2cHandleSCLIsr(%p)", pvI2CDev);
    __i2cExit("i2cHandleSCLIsr()");
}
i2cHandleSDAIsr()
static void IRAM_ATTR i2cHandleSDAIsr (void * pvI2CDev) static
Handle SDA interrupt in slave mode.
Parameters
pv Pointer to i2cDev_t
Definition at line 61 of file i2c.h.
{
    __i2cEntry("i2cHandleSDAIsr(%p)", pvI2CDev);
    __i2cExit("i2cHandleSDAIsr()");
}
i2cReceiveBuffer()
def i2cReceiveBuffer (i2cDev_t * dev, uint8_t addr7, uint8_t rw, flag_t extConf)
Receive all bytes in the transmit buffer.
Parameters
dev Pointer to i2cDev_t
addr7 7 bits slave address
rw Read/Write bit (I2C_WRITE_MODE, I2C_READ_MODE)
extConf Extent config, check I2C_EXTENT_CONFIG_BIT_ORDER enum for more details.
Returns
Default return status
Make start condition
Send address frame
Get and process returned bit
Mono SCL pulse (9th pulse)
Mono SCL pulse (9th pulse)
Definition at line 355 of file i2c.c.
{
    __I2C_ASSERT_DEV_OK1(STR(i2cSendBuffer), dev, STR(dev));
    if(__hasFlagBitClr(extConf, I2C_DIS_ENTRY_CRITICAL_SEC)) vPortEnterCritical(&(dev->mutex));
    if(__hasFlagBitClr(extConf, I2C_DIS_START_CONDI)) i2cStartCondition(dev);
    i2cSendAddressFrame(dev, addr7, rw);
    if(i2cGetReturnBit(dev) == I2C_NACK) {
        __i2cErr("[i2cReceiveBuffer] Got NACK after send address frame!");
        goto i2cReceiveBuffer_ReturnERR;
    }
    if(__hasFlagBitSet(extConf, I2C_RESET_TX_INDEX))
        i2cResetIndexTransmitBuffer(dev);
    if(__hasFlagBitSet(extConf, I2C_RESET_RX_INDEX))
        i2cResetIndexReceiveBuffer(dev);
    def receivedByte = 0;
    REP(i, dev->txIndByte, dev->txSize){
        receivedByte = i2cReceiveByte(dev);
        __i2cLog1("Received [0x%04x]", receivedByte);
        if(receivedByte < 0){
            __sys_err("[i2cReceiveBuffer] The i2cReceiveByte has returned [%d]", receivedByte);
            __i2cSetSDA(dev, I2C_NACK);
            __i2cDelay(500000/__i2cFreq(dev));
            __i2cSetSCL(dev, HIGH);
            __i2cDelay(500000/__i2cFreq(dev));
            __i2cSetSCL(dev, LOW);
            goto i2cReceiveBuffer_ReturnERR;
        }else{
            ((uint8_t*)(dev->txPtr))[(dev->rxIndByte)++] = receivedByte;
            __i2cSetSDA(dev, I2C_ACK);
            __i2cDelay(500000/__i2cFreq(dev));
            __i2cSetSCL(dev, HIGH);
            __i2cDelay(500000/__i2cFreq(dev));
            __i2cSetSCL(dev, LOW);
        }
    }
    if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
    if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
    return OKE;
    i2cReceiveBuffer_ReturnERR:
        if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
        if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
        return ERR;
}
References __i2cFreq(), __i2cSetSCL(), __i2cSetSDA(), ERR, HIGH, I2C_ACK, I2C_DIS_ENTRY_CRITICAL_SEC, I2C_DIS_EXIT_CRITICAL_SEC, I2C_DIS_START_CONDI, I2C_DIS_STOP_CONDI, I2C_NACK, I2C_RESET_RX_INDEX, I2C_RESET_TX_INDEX, i2cGetReturnBit(), i2cReceiveByte(), i2cResetIndexReceiveBuffer(), i2cResetIndexTransmitBuffer(), i2cSendAddressFrame(), i2cStartCondition(), i2cStopCondition(), LOW, OKE, i2cDev_t::rxIndByte, i2cDev_t::txIndByte, i2cDev_t::txPtr, and i2cDev_t::txSize.
i2cSendBuffer()
def i2cSendBuffer (i2cDev_t * dev, uint8_t addr7, uint8_t rw, flag_t extConf)
Send all bytes in the transmit buffer.
Parameters
dev Pointer to i2cDev_t
addr7 7 bits slave address
rw Read/Write bit (I2C_WRITE_MODE, I2C_READ_MODE)
extConf Extent config, check I2C_EXTENT_CONFIG_BIT_ORDER enum for more details.
Returns
Default return status
Make start condition
Send address frame
Get and process returned bit
Send byte[i]
Get and process returned bit
Definition at line 297 of file i2c.c.
{
    __i2cEntry("i2cSendBuffer(%p, %d, %d, 0x%04x)", dev, addr7, rw, extConf);
    __I2C_ASSERT_DEV_OK1(STR(i2cSendBuffer), dev, STR(dev));
    __i2cLog("[i2cSendBuffer] I2C_DIS_ENTRY_CRITICAL_SEC : %d", __hasFlagBitClr(extConf, I2C_DIS_ENTRY_CRITICAL_SEC));
    __i2cLog("[i2cSendBuffer] I2C_DIS_START_CONDI : %d", __hasFlagBitClr(extConf, I2C_DIS_START_CONDI));
    __i2cLog("[i2cSendBuffer] I2C_DIS_STOP_CONDI : %d", __hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI));
    __i2cLog("[i2cSendBuffer] I2C_DIS_EXIT_CRITICAL_SEC : %d", __hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC));
    __i2cLog("[i2cSendBuffer] I2C_SKIP_ADDR_FRAME : %d", __hasFlagBitClr(extConf, I2C_SKIP_ADDR_FRAME));
    if(__hasFlagBitClr(extConf, I2C_DIS_ENTRY_CRITICAL_SEC)) vPortEnterCritical(&(dev->mutex));
    if(__hasFlagBitClr(extConf, I2C_DIS_START_CONDI)) i2cStartCondition(dev);
    if(__hasFlagBitClr(extConf, I2C_SKIP_ADDR_FRAME)){
        __i2cLog1("[i2cSendBuffer] Send sdress frame [0x%04x | %d]", addr7, rw);
        i2cSendAddressFrame(dev, addr7, rw);
        if(i2cGetReturnBit(dev) == I2C_NACK) {
            __i2cErr("[i2cSendBuffer] Got NACK after send address frame!");
            goto i2cSendBuffer_ReturnERR;
        }
    }
    if(__hasFlagBitSet(extConf, I2C_RESET_TX_INDEX))
        i2cResetIndexTransmitBuffer(dev);
    if(__hasFlagBitSet(extConf, I2C_RESET_RX_INDEX))
        i2cResetIndexReceiveBuffer(dev);
    REP(i, dev->txIndByte, dev->txSize){
        __i2cLog1("[i2cSendBuffer] Send [0x%04x]", ((char*)(dev->txPtr))[i]);
        i2cSendDataFrame(dev, ((char*)(dev->txPtr))[i]);
        if(i2cGetReturnBit(dev) == I2C_NACK) {
            __i2cLog1("[i2cSendBuffer] Got NACK!");
            __i2cErr("[i2cSendBuffer] Got NACK after send byte[%d] in buffer!", i);
            goto i2cSendBuffer_ReturnERR;
        }
        __i2cLog1("[i2cSendBuffer] Got ACK");
    }
    if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
    if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
    __i2cExit("i2cSendBuffer() : %s", STR(OKE));
    return OKE;
    i2cSendBuffer_ReturnERR:
        if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
        if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
        __i2cExit("i2cSendBuffer() : %s", STR(ERR));
        return ERR;
}
References ERR, I2C_DIS_ENTRY_CRITICAL_SEC, I2C_DIS_EXIT_CRITICAL_SEC, I2C_DIS_START_CONDI, I2C_DIS_STOP_CONDI, I2C_NACK, I2C_RESET_RX_INDEX, I2C_RESET_TX_INDEX, I2C_SKIP_ADDR_FRAME, i2cGetReturnBit(), i2cResetIndexReceiveBuffer(), i2cResetIndexTransmitBuffer(), i2cSendAddressFrame(), i2cSendDataFrame(), i2cStartCondition(), i2cStopCondition(), OKE, i2cDev_t::txIndByte, i2cDev_t::txPtr, and i2cDev_t::txSize.
Referenced by oledFlush(), oledResetView(), and startupOLEDDevice().
i2cSendByte()
def i2cSendByte (i2cDev_t * dev, uint8_t addr7, uint8_t rw, uint8_t byte, flag_t extConf)
Send a specified byte.
Parameters
dev Pointer to i2cDev_t
addr7 7 bits slave address
rw Read/Write bit (I2C_WRITE_MODE, I2C_READ_MODE)
byte Specified byte to be sent
extConf Extent config, check I2C_EXTENT_CONFIG_BIT_ORDER enum for more details.
Returns
Default return status
Make start condition
Send address frame
Get and process returned bit
Send byte high
Get and process returned bit
Definition at line 223 of file i2c.c.
{
    __I2C_ASSERT_DEV_OK1(STR(i2cSendByte), dev, STR(dev));
    if(__hasFlagBitClr(extConf, I2C_DIS_ENTRY_CRITICAL_SEC)) vPortEnterCritical(&(dev->mutex));
    if(__hasFlagBitClr(extConf, I2C_DIS_START_CONDI)) i2cStartCondition(dev);
    i2cSendAddressFrame(dev, addr7, rw);
    if(i2cGetReturnBit(dev) == I2C_NACK) {
        __i2cErr("[i2cSendByte] Got NACK after send address frame!");
        goto i2cSendByte_ReturnERR;
    }
    i2cSendDataFrame(dev, byte);
    if(i2cGetReturnBit(dev) == I2C_NACK) {
        __i2cErr("[i2cSendByte] Got NACK after send byte high!");
        goto i2cSendByte_ReturnERR;
    }
    if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
    if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
    return OKE;
    i2cSendByte_ReturnERR:
        if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
        if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
        return ERR;
}
References ERR, I2C_DIS_ENTRY_CRITICAL_SEC, I2C_DIS_EXIT_CRITICAL_SEC, I2C_DIS_START_CONDI, I2C_DIS_STOP_CONDI, I2C_NACK, i2cGetReturnBit(), i2cSendAddressFrame(), i2cSendDataFrame(), i2cStartCondition(), i2cStopCondition(), and OKE.
Referenced by oledFlush().
i2cSendDoubleByte()
def i2cSendDoubleByte (i2cDev_t * dev, uint8_t addr7, uint8_t rw, uint8_t byteHigh, uint8_t byteLow, flag_t extConf)
Send a specified double byte.
Parameters
dev Pointer to i2cDev_t
addr7 7 bits slave address
rw Read/Write bit (I2C_WRITE_MODE, I2C_READ_MODE)
byteHigh Specified byte-High to be sent
byteLow Specified byte-Low to be sent
extConf Extent config, check I2C_EXTENT_CONFIG_BIT_ORDER enum for more details.
Returns
Default return status
Make start condition
Send address frame
Get and process returned bit
Send byte high
Get and process returned bit
Send byte low
Get and process returned bit
Definition at line 255 of file i2c.c.
{
    __i2cEntry("i2cSendDoubleByte(%p, %d, %d, 0x%02x, 0x%02x, 0x%04x)", dev, addr7, rw, byteHigh, byteLow, extConf);
    __I2C_ASSERT_DEV_OK1(STR(i2cSendDoubleByte), dev, STR(dev));
    if(__hasFlagBitClr(extConf, I2C_DIS_ENTRY_CRITICAL_SEC)) vPortEnterCritical(&(dev->mutex));
    if(__hasFlagBitClr(extConf, I2C_DIS_START_CONDI)) i2cStartCondition(dev);
    i2cSendAddressFrame(dev, addr7, rw);
    if(i2cGetReturnBit(dev) == I2C_NACK) {
        __i2cErr("[i2cSendDoubleByte] Got NACK after send address frame!");
        goto i2cSendDoubleByte_ReturnERR;
    }
    i2cSendDataFrame(dev, byteHigh);
    if(i2cGetReturnBit(dev) == I2C_NACK) {
        __i2cErr("[i2cSendDoubleByte] Got NACK after send byte high!");
        goto i2cSendDoubleByte_ReturnERR;
    }
    i2cSendDataFrame(dev, byteLow);
    if(i2cGetReturnBit(dev) == I2C_NACK) {
        __i2cErr("[i2cSendDoubleByte] Got NACK after send byte low!");
        goto i2cSendDoubleByte_ReturnERR;
    }
    if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
    if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
    return OKE;
    i2cSendDoubleByte_ReturnERR:
        if(__hasFlagBitClr(extConf, I2C_DIS_STOP_CONDI)) i2cStopCondition(dev);
        if(__hasFlagBitClr(extConf, I2C_DIS_EXIT_CRITICAL_SEC)) vPortExitCritical(&(dev->mutex));
        __i2cExit("i2cSendDoubleByte : %s", STR(ERR));
        return ERR;
}
References ERR, I2C_DIS_ENTRY_CRITICAL_SEC, I2C_DIS_EXIT_CRITICAL_SEC, I2C_DIS_START_CONDI, I2C_DIS_STOP_CONDI, I2C_NACK, i2cGetReturnBit(), i2cSendAddressFrame(), i2cSendDataFrame(), i2cStartCondition(), i2cStopCondition(), and OKE.
Referenced by oledOff(), oledOn(), oledShowRAMContent(), and oledTurnOnAllPixels().
i2cSetReceiveBuffer()
def i2cSetReceiveBuffer (i2cDev_t * dev, void * rBuff, size_t size)
Set receive buffer for I2C.
Parameters
dev Pointer to i2cDev_t
rBuff Pointer to receive buffer
size Size of transmit buffer (in bytes)
Returns
Default return status
Reset rxPtr and rxSize
Definition at line 185 of file i2c.c.
{
    __i2cEntry("i2cSetReceiveBuffer(%p, %p, %d)", dev, rxPtr, size);
    if(__is_null(dev)){
        __i2cErr("dev = %p is invalid!", dev);
        goto i2cSetReceiveBuffer_ReturnERR_NULL;
    }
    if(__is_null(rxPtr)){
        __i2cErr("rxPtr = %p is invalid!", rxPtr);
        goto i2cSetReceiveBuffer_ReturnERR_NULL;
    }
    if(__isnot_positive(size)){
        __i2cErr("size = %d is invalid!", size);
        goto i2cSetReceiveBuffer_ReturnERR_NULL;
    }
    dev->rxPtr = rxPtr;
    dev->rxSize = size;
    dev->rxIndBit = 0;
    dev->rxIndByte = 0;
    __i2cExit("i2cSetReceiveBuffer() : %s", STR(OKE));
    return OKE;
    i2cSetReceiveBuffer_ReturnERR_NULL:
    dev->rxPtr = NULL;
    dev->rxSize = 0;
    dev->rxIndBit = 0;
    dev->rxIndByte = 0;
    __i2cExit("i2cSetReceiveBuffer() : %s", STR(ERR_NULL));
    return ERR_NULL;
}
References ERR_NULL, OKE, i2cDev_t::rxIndBit, i2cDev_t::rxIndByte, i2cDev_t::rxPtr, and i2cDev_t::rxSize.
i2cSetTransmitBuffer()
def i2cSetTransmitBuffer (i2cDev_t * dev, void * tBuff, size_t size)
Set transmit buffer for I2C.
Parameters
dev Pointer to i2cDev_t
tBuff Pointer to transmit buffer
size Size of transmit buffer (in bytes)
Returns
Default return status
Reset txPtr and txSize
Definition at line 148 of file i2c.c.
{
    __i2cEntry(" i2cSetTransmitBuffer(%p, %p, %d)", dev,txPtr,size);
    if(__is_null(dev)){
        __i2cErr("dev = %p is invalid!", dev);
        goto  i2cSetTransmitBuffer_ReturnERR_NULL;
    }
    if(__is_null(txPtr)){
        __i2cErr("txPtr = %p is invalid!", txPtr);
        goto  i2cSetTransmitBuffer_ReturnERR_NULL;
    }
    if(__isnot_positive(size)){
        __i2cErr("size = %d is invalid!", size);
        goto  i2cSetTransmitBuffer_ReturnERR_NULL;
    }
    dev->txPtr = txPtr;
    dev->txSize = size;
    dev->txIndBit = 0;
    dev->txIndByte = 0;
    __i2cExit(" i2cSetTransmitBuffer() : %s", STR(OKE));
    return OKE;
    i2cSetTransmitBuffer_ReturnERR_NULL:
        dev->txPtr = NULL;
        dev->txSize = 0;
        dev->txIndBit = 0;
        dev->txIndByte = 0;
        __i2cExit(" i2cSetTransmitBuffer() : %s", STR(ERR_NULL));
        return ERR_NULL;
}
References ERR_NULL, OKE, i2cDev_t::txIndBit, i2cDev_t::txIndByte, i2cDev_t::txPtr, and i2cDev_t::txSize.
Referenced by oledFlush(), and startupOLEDDevice().
startupI2CDevice()
def startupI2CDevice (i2cDev_t * dev)
Startup the I2C device (initialize GPIO and configs)
Parameters
dev Pointer to i2cDev_t
Returns
Default return status
MASTER MODE ///
SLAVE MODE ///
TODO: Fix GPIO mask
Definition at line 74 of file i2c.c.
{
    __i2cEntry("startupI2CDevice(%p)", dev);
    if(__is_null(dev)) {
        __i2cErr("dev is null!");
        __i2cExit("startupI2CDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
    }
    if(__hasFlagBitSet(dev->conf, I2C_MODE) == I2C_MASTER){
        __i2cLog("Set up for I2C master mode...");
        gpio_config_t sdaPin = {
            .intr_type = GPIO_INTR_DISABLE,
            .mode = GPIO_MODE_INPUT_OUTPUT_OD,
            .pin_bit_mask = __mask32(dev->sda),
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .pull_up_en = GPIO_PULLUP_ENABLE,
        };
        gpio_config(&sdaPin);
        gpio_config_t sclPin = {
            .intr_type = GPIO_INTR_DISABLE,
            .mode = GPIO_MODE_OUTPUT,
            .pin_bit_mask = __mask32(dev->scl),
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .pull_up_en = GPIO_PULLUP_DISABLE,
        };
        gpio_config(&sclPin);
    }else{
        __i2cLog("Set up for I2C slave mode");
        gpio_config_t sdaPin = {
            .intr_type = GPIO_INTR_DISABLE,
            .mode = GPIO_MODE_INPUT_OUTPUT_OD,
            .pin_bit_mask = __mask32(dev->sda),
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .pull_up_en = GPIO_PULLDOWN_DISABLE,
        };
        gpio_config(&sdaPin);
        gpio_config_t sclPin = {
            .intr_type = GPIO_INTR_DISABLE,
            .mode = GPIO_MODE_INPUT,
            .pin_bit_mask = __mask32(dev->scl),
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .pull_up_en = GPIO_PULLUP_DISABLE,
        };
        gpio_config(&sclPin);
        // Install ISR service if not installed
        esp_err_t r = gpio_install_isr_service(ESP_INTR_FLAG_IRAM);
        if (r != ESP_OK && r != ESP_ERR_INVALID_STATE) {
            __i2cErr("gpio_install_isr_service() : %d", r);
            __i2cExit("startupI2CDevice() : %s", STR(ERR));
            return ERR;
        }
        if(__isnot_negative(dev->sda)){
            gpio_set_intr_type(dev->sda, GPIO_INTR_ANYEDGE);
            gpio_isr_handler_add(dev->sda, i2cHandleSDAIsr, dev);
        }
        if(__isnot_negative(dev->scl)){
            gpio_set_intr_type(dev->scl, GPIO_INTR_ANYEDGE);
            gpio_isr_handler_add(dev->scl, i2cHandleSCLIsr, dev);
        }
    }
    __i2cExit("startupI2CDevice() : %s", STR(OKE));
    return OKE;
}
References i2cDev_t::conf, ERR, ERR_NULL, I2C_MASTER, I2C_MODE, OKE, i2cDev_t::scl, and i2cDev_t::sda.
Referenced by startupOLEDDevice().