DO-AN-02: comDriver/i2c/i2cHelper.h File Reference
i2cHelper.h File Reference
#include "../../helper/general.h"
#include "i2cDefinition.h"
#include "i2cLog.h"
Macros
#define __I2C_ASSERT_DEV_OK(funcName, i2cDev, devName)
Assert that the I2C device pointer is valid. If not, call esp_restart().
#define __I2C_ASSERT_DEV_OK1(funcName, i2cDev, devName)
Assert that the I2C device pointer is valid. If not, call return ERR_NULL.
#define __I2C_ASSERT_PIN_OK(funcName, pinValue, pinName)
Assert that the I2C pin configuration is valid.
#define __i2cDelay(us) esp_rom_delay_us(us)
Delay function wrapper for I2C.
Functions
static uint32_t __i2cFreq (i2cDev_t *dev)
Get I2C bus frequency of a given device.
static pin_t __i2cSCL (i2cDev_t *dev)
Get the SCL (clock) pin of a given I2C device.
static pin_t __i2cSDA (i2cDev_t *dev)
Get the SDA (data) pin of a given I2C device.
static void __i2cSetSDA (i2cDev_t *dev, def level)
Set logic level for SDA line of an I2C device.
static void __i2cSetSCL (i2cDev_t *dev, def level)
Set logic level for SCL line of an I2C device.
static def __i2cGetSDA (i2cDev_t *dev)
Read the current logic level of SDA line.
static def __i2cGetSCL (i2cDev_t *dev)
Read the current logic level of SCL line.
static void i2cStartCondition (i2cDev_t *dev)
Generate I2C START condition.
static void i2cStopCondition (i2cDev_t *dev)
Generate I2C STOP condition.
static void i2cSendAddressFrame (i2cDev_t *dev, uint8_t addr7, uint8_t rw)
Send I2C address frame with R/W bit.
static void i2cSendDataFrame (i2cDev_t *dev, uint8_t byte)
Send one I2C data frame (8-bit)
static def i2cGetReturnBit (i2cDev_t *dev)
Release SDA, then get return bit.
static def i2cResetIndexTransmitBuffer (i2cDev_t *dev)
Reset I2C transmit buffer index (bit/byte) to zero.
static def i2cResetIndexReceiveBuffer (i2cDev_t *dev)
Reset I2C receive buffer index (bit/byte) to zero.
static def i2cClearTransmitBuffer (i2cDev_t *dev)
Clear I2C transmit buffer and reset its indices.
static def i2cClearReceiveBuffer (i2cDev_t *dev)
Clear I2C receive buffer and reset its indices.
static def i2cReceiveByte (i2cDev_t *dev)
Just receive 8 bit from SDA (without start/stop condition and send anything)
Macro Definition Documentation
__I2C_ASSERT_DEV_OK
#define __I2C_ASSERT_DEV_OK (funcName, i2cDev, devName)
Value:
    do {                                                   \
        if(__is_null(i2cDev)){                             \
            __i2cErr("[%s] %s = %p is invalid",            \
                            funcName, devName, i2cDev);    \
            esp_restart();                                 \
            __builtin_unreachable();                       \
        }                                                  \
    } while(0)
Assert that the I2C device pointer is valid. If not, call esp_restart().
Parameters
funcName Function name where the check is invoked.
i2cDev Pointer to the I2C device.
devName String name of the I2C device variable.
Definition at line 18 of file i2cHelper.h.
       {                                                   \
        if(__is_null(i2cDev)){                             \
            __i2cErr("[%s] %s = %p is invalid",            \
                            funcName, devName, i2cDev);    \
            esp_restart();                                 \
            __builtin_unreachable();                       \
        }                                                  \
    } while(0)
__I2C_ASSERT_DEV_OK1
#define __I2C_ASSERT_DEV_OK1 (funcName, i2cDev, devName)
Value:
    do {                                                   \
        if(__is_null(i2cDev)){                             \
            __i2cErr("[%s] %s = %p is invalid",            \
                            funcName, devName, i2cDev);    \
            return ERR_NULL;                               \
        }                                                  \
    } while(0)
Assert that the I2C device pointer is valid. If not, call return ERR_NULL.
Parameters
funcName Function name where the check is invoked.
i2cDev Pointer to the I2C device.
devName String name of the I2C device variable.
Returns
call ERR_NULL if dev is null.
Definition at line 33 of file i2cHelper.h.
       {                                                   \
        if(__is_null(i2cDev)){                             \
            __i2cErr("[%s] %s = %p is invalid",            \
                            funcName, devName, i2cDev);    \
            return ERR_NULL;                               \
        }                                                  \
    } while(0)
__I2C_ASSERT_PIN_OK
#define __I2C_ASSERT_PIN_OK (funcName, pinValue, pinName)
Value:
    do {                                                    \
        if(__isnot_positive(pinValue)){                     \
            __i2cErr("[%s] %s = %d is invalid",             \
                     funcName, pinName, pinValue);          \
            esp_restart();                                  \
            __builtin_unreachable();                        \
        }                                                   \
    } while(0)
Assert that the I2C pin configuration is valid.
Parameters
funcName Function name where the check is invoked.
pinValue Numeric pin value.
pinName String name of the pin variable.
Definition at line 47 of file i2cHelper.h.
       {                                                    \
        if(__isnot_positive(pinValue)){                     \
            __i2cErr("[%s] %s = %d is invalid",             \
                     funcName, pinName, pinValue);          \
            esp_restart();                                  \
            __builtin_unreachable();                        \
        }                                                   \
    } while(0)
__i2cDelay
#define __i2cDelay (us) esp_rom_delay_us(us)
Delay function wrapper for I2C.
Parameters
us Delay time in microseconds.
Definition at line 59 of file i2cHelper.h.
Function Documentation
__i2cFreq()
static uint32_t __i2cFreq (i2cDev_t * dev) inline static
Get I2C bus frequency of a given device.
Parameters
dev Pointer to I2C device.
Returns
Frequency in Hz.
Note
Will reset system if frequency is invalid.
Definition at line 66 of file i2cHelper.h.
{
    __I2C_ASSERT_PIN_OK("__i2cFreq", dev->freq, STR(freq));
    return dev->freq;
}
References i2cDev_t::freq.
Referenced by i2cGetReturnBit(), i2cReceiveBuffer(), i2cReceiveByte(), i2cSendAddressFrame(), i2cSendDataFrame(), i2cStartCondition(), and i2cStopCondition().
__i2cGetSCL()
static def __i2cGetSCL (i2cDev_t * dev) inline static
Read the current logic level of SCL line.
Parameters
dev Pointer to I2C device.
Returns
Current logic level of SCL (0 or 1).
Note
Will reset system if SCL pin is invalid.
Definition at line 132 of file i2cHelper.h.
{
    __I2C_ASSERT_PIN_OK(STR(__i2cGetSCL), dev->scl, STR(dev->scl));
    return boolCast(GPIO.in & __mask32(dev->scl));
}
References i2cDev_t::scl.
__i2cGetSDA()
static def __i2cGetSDA (i2cDev_t * dev) inline static
Read the current logic level of SDA line.
Parameters
dev Pointer to I2C device.
Returns
Current logic level of SDA (0 or 1).
Note
Will reset system if SDA pin is invalid.
Definition at line 122 of file i2cHelper.h.
{
    // __I2C_ASSERT_PIN_OK(STR(__i2cGetSDA), dev->sda, STR(dev->sda));
    return boolCast(GPIO.in & __mask32(dev->sda));
}
Referenced by i2cGetReturnBit(), and i2cReceiveByte().
__i2cSCL()
static pin_t __i2cSCL (i2cDev_t * dev) inline static
Get the SCL (clock) pin of a given I2C device.
Parameters
dev Pointer to I2C device.
Returns
Pin number for SCL.
Note
Will reset system if pin is invalid.
Definition at line 76 of file i2cHelper.h.
{
    __I2C_ASSERT_PIN_OK(STR(__i2cSCL), dev->sda, STR(dev->sda));
    return dev->scl;
}
References i2cDev_t::scl, and i2cDev_t::sda.
__i2cSDA()
static pin_t __i2cSDA (i2cDev_t * dev) inline static
Get the SDA (data) pin of a given I2C device.
Parameters
dev Pointer to I2C device.
Returns
Pin number for SDA.
Note
Will reset system if pin is invalid.
Definition at line 86 of file i2cHelper.h.
{
    __I2C_ASSERT_PIN_OK(STR(__i2cSDA), dev->scl, STR(dev->scl));
    return dev->sda;
}
References i2cDev_t::scl, and i2cDev_t::sda.
__i2cSetSCL()
static void __i2cSetSCL (i2cDev_t * dev, def level) inline static
Set logic level for SCL line of an I2C device.
Parameters
dev Pointer to I2C device.
level Logic level (0 = low, 1 = high).
Note
Will reset system if SCL pin is invalid.
Definition at line 109 of file i2cHelper.h.
{
    __I2C_ASSERT_PIN_OK(STR(__i2cSetSCL), dev->scl, STR(dev->scl));
    if(level)
        GPIO.out_w1ts = __mask32(dev->scl);
    else
        GPIO.out_w1tc = __mask32(dev->scl);
}
References i2cDev_t::scl.
Referenced by i2cGetReturnBit(), i2cReceiveBuffer(), i2cReceiveByte(), i2cSendAddressFrame(), i2cSendDataFrame(), i2cStartCondition(), and i2cStopCondition().
__i2cSetSDA()
static void __i2cSetSDA (i2cDev_t * dev, def level) inline static
Set logic level for SDA line of an I2C device.
Parameters
dev Pointer to I2C device.
level Logic level (0 = low, 1 = high).
Note
Will reset system if SDA pin is invalid.
Definition at line 96 of file i2cHelper.h.
{
    __I2C_ASSERT_PIN_OK(STR(__i2cSetSDA), dev->sda, STR(dev->sda));
    if(level)
        GPIO.out_w1ts = __mask32(dev->sda);
    else
        GPIO.out_w1tc = __mask32(dev->sda);
}
References i2cDev_t::sda.
Referenced by i2cGetReturnBit(), i2cReceiveBuffer(), i2cSendAddressFrame(), i2cSendDataFrame(), i2cStartCondition(), and i2cStopCondition().
i2cClearReceiveBuffer()
static def i2cClearReceiveBuffer (i2cDev_t * dev) inline static
Clear I2C receive buffer and reset its indices.
Parameters
dev Pointer to I2C device context.
Returns
OKE on success, ERR_NULL if dev is null.
Definition at line 306 of file i2cHelper.h.
{
    if(__is_null(dev)){
        __i2cErr("[i2cClearReceiveBuffer] Dev is null!");
        return ERR_NULL;
    }
    (dev->rxIndBit) = 0;
    (dev->rxIndByte) = 0;
    memset(dev->rxPtr, 0, dev->rxSize);
    return OKE;
}
References ERR_NULL, OKE, i2cDev_t::rxIndBit, i2cDev_t::rxIndByte, i2cDev_t::rxPtr, and i2cDev_t::rxSize.
i2cClearTransmitBuffer()
static def i2cClearTransmitBuffer (i2cDev_t * dev) inline static
Clear I2C transmit buffer and reset its indices.
Parameters
dev Pointer to I2C device context.
Returns
OKE on success, ERR_NULL if dev is null.
Definition at line 291 of file i2cHelper.h.
{
    if(__is_null(dev)){
        __i2cErr("[i2cClearTransmitBuffer] Dev is null!");
        return ERR_NULL;
    }
    (dev->txIndBit) = 0;
    (dev->txIndByte) = 0;
    memset(dev->txPtr, 0, dev->txSize);
    return OKE;
}
References ERR_NULL, OKE, i2cDev_t::txIndBit, i2cDev_t::txIndByte, i2cDev_t::txPtr, and i2cDev_t::txSize.
i2cGetReturnBit()
static def i2cGetReturnBit (i2cDev_t * dev) inline static
Release SDA, then get return bit.
Parameters
dev I2c device
Returns
Release SDA line
Make raising edge
Definition at line 242 of file i2cHelper.h.
{
    __i2cSetSDA(dev, HIGH);
    __i2cSetSCL(dev, LOW);
    __i2cDelay(500000/__i2cFreq(dev));
    __i2cSetSCL(dev, HIGH);
    __i2cDelay(500000/__i2cFreq(dev));
    def ret = __i2cGetSDA(dev);
    __i2cSetSCL(dev, LOW);
    return ret;
}
References __i2cFreq(), __i2cGetSDA(), __i2cSetSCL(), __i2cSetSDA(), HIGH, and LOW.
Referenced by i2cReceiveBuffer(), i2cSendBuffer(), i2cSendByte(), and i2cSendDoubleByte().
i2cReceiveByte()
static def i2cReceiveByte (i2cDev_t * dev) inline static
Just receive 8 bit from SDA (without start/stop condition and send anything)
Parameters
dev Pointer to I2C device context.
Returns
A non negative number (received byte) if success, negative if error.
Definition at line 321 of file i2cHelper.h.
{
    def rcvByte = 0;
    __i2cSetSCL(dev, LOW);
    REP(i, 0, 8){
        __i2cDelay(500000/__i2cFreq(dev));
        __i2cSetSCL(dev, HIGH);
        rcvByte = (rcvByte << 1) | __i2cGetSDA(dev);
        __i2cDelay(500000/__i2cFreq(dev));
        __i2cSetSCL(dev, LOW);
    }
    return rcvByte;
}
References __i2cFreq(), __i2cGetSDA(), __i2cSetSCL(), HIGH, and LOW.
Referenced by i2cReceiveBuffer().
i2cResetIndexReceiveBuffer()
static def i2cResetIndexReceiveBuffer (i2cDev_t * dev) inline static
Reset I2C receive buffer index (bit/byte) to zero.
Parameters
dev Pointer to I2C device context.
Returns
OKE on success, ERR_NULL if dev is null.
Definition at line 277 of file i2cHelper.h.
{
    if(__is_null(dev)){
        __i2cErr("[i2cResetIndexReceiveBuffer] Dev is null!");
        return ERR_NULL;
    }
    (dev->rxIndBit) = 0;
    (dev->rxIndByte) = 0;
    return OKE;
}
References ERR_NULL, OKE, i2cDev_t::rxIndBit, and i2cDev_t::rxIndByte.
Referenced by i2cReceiveBuffer(), and i2cSendBuffer().
i2cResetIndexTransmitBuffer()
static def i2cResetIndexTransmitBuffer (i2cDev_t * dev) inline static
Reset I2C transmit buffer index (bit/byte) to zero.
Parameters
dev Pointer to I2C device context.
Returns
OKE on success, ERR_NULL if dev is null.
Definition at line 263 of file i2cHelper.h.
{
    if(__is_null(dev)){
        __i2cErr("[i2cResetIndexTransmitBuffer] Dev is null!");
        return ERR_NULL;
    }
    (dev->txIndBit) = 0;
    (dev->txIndByte) = 0;
    return OKE;
}
References ERR_NULL, OKE, i2cDev_t::txIndBit, and i2cDev_t::txIndByte.
Referenced by i2cReceiveBuffer(), and i2cSendBuffer().
i2cSendAddressFrame()
static void i2cSendAddressFrame (i2cDev_t * dev, uint8_t addr7, uint8_t rw) inline static
Send I2C address frame with R/W bit.
Parameters
dev Pointer to I2C device
addr7 7-bit slave address
rw Read/Write mode (I2C_WRITE_MODE or I2C_READ_MODE)
WRITE MODE
SLAVE MODE
Start sending 8 bit of address frame from MSB to LSB
Export bit data to SDA
Make mono pulse of SCL
Definition at line 190 of file i2cHelper.h.
{
    uint8_t addressFrame = 0;
    if((rw & 1U) == I2C_WRITE_MODE){
        addressFrame = (addr7 << 1);
    }else{
        addressFrame = (addr7 << 1) | 1U;
    }
    // __i2cLog1("addressFrame = 0x%04x", addressFrame);
    for(uint8_t mask = 0x80; mask; mask  >>= 1){
        __i2cSetSDA(dev, boolCast(mask & addressFrame));
        __i2cDelay(500000/__i2cFreq(dev));
        __i2cSetSCL(dev, HIGH);
        __i2cDelay(500000/__i2cFreq(dev));
        __i2cSetSCL(dev, LOW);
    }
}
References __i2cFreq(), __i2cSetSCL(), __i2cSetSDA(), HIGH, I2C_WRITE_MODE, and LOW.
Referenced by i2cReceiveBuffer(), i2cSendBuffer(), i2cSendByte(), and i2cSendDoubleByte().
i2cSendDataFrame()
static void i2cSendDataFrame (i2cDev_t * dev, uint8_t byte) inline static
Send one I2C data frame (8-bit)
Parameters
dev Pointer to I2C device
byte Data byte to send
<– small fix: should assign from input byte
Start sending 8 bit of data frame from MSB to LSB
Export bit data to SDA
Make mono pulse of SCL
Definition at line 219 of file i2cHelper.h.
{
    uint32_t dataFrame = byte;
    // __i2cLog1("dataFrame = 0x%04x", dataFrame);
    for(uint32_t mask = 0x80; mask; mask  >>= 1){
        __i2cSetSDA(dev, boolCast(mask & dataFrame));
        __i2cDelay(500000/__i2cFreq(dev));
        __i2cSetSCL(dev, HIGH);
        __i2cDelay(500000/__i2cFreq(dev));
        __i2cSetSCL(dev, LOW);
    }
}
References __i2cFreq(), __i2cSetSCL(), __i2cSetSDA(), HIGH, and LOW.
Referenced by i2cSendBuffer(), i2cSendByte(), and i2cSendDoubleByte().
i2cStartCondition()
static void i2cStartCondition (i2cDev_t * dev) inline static
Generate I2C START condition.
Parameters
dev Pointer to I2C device
Release both SCL, SDA line
Wait for both SCL and SDA are stable (a half of SCL period)
Make start condition (SDA down to LOW when SCL is HIGH)
Wait for a quarter of SCL period
Pull SCL down for 1st clock pulse
Definition at line 140 of file i2cHelper.h.
{
    __i2cDelay(250000/(__i2cFreq(dev)));
    __i2cSetSCL(dev, HIGH);
    __i2cSetSDA(dev, HIGH);
    __i2cDelay(500000/(__i2cFreq(dev)));
    __i2cSetSDA(dev, LOW);
    __i2cDelay(250000/(__i2cFreq(dev)));
    __i2cSetSCL(dev, LOW);
}
References __i2cFreq(), __i2cSetSCL(), __i2cSetSDA(), HIGH, and LOW.
Referenced by i2cReceiveBuffer(), i2cSendBuffer(), i2cSendByte(), and i2cSendDoubleByte().
i2cStopCondition()
static void i2cStopCondition (i2cDev_t * dev) inline static
Generate I2C STOP condition.
Parameters
dev Pointer to I2C device
Make sure both SCL, SDA line are LOW
Wait for both SCL and SDA are stable (a half of SCL period)
Pull SCL up to HIGH for stop condition
Wait for a quarter of SCL period
Make stop condition (SDA is pulled up to HIGH when SCL is HIGH)
Definition at line 164 of file i2cHelper.h.
{
    __i2cDelay(250000/(__i2cFreq(dev)));
    __i2cSetSCL(dev, LOW);
    __i2cSetSDA(dev, LOW);
    __i2cDelay(500000/(__i2cFreq(dev)));
    __i2cSetSCL(dev, HIGH);
    __i2cDelay(250000/(__i2cFreq(dev)));
    __i2cSetSDA(dev, HIGH);
}
References __i2cFreq(), __i2cSetSCL(), __i2cSetSDA(), HIGH, and LOW.
Referenced by i2cReceiveBuffer(), i2cSendBuffer(), i2cSendByte(), and i2cSendDoubleByte().