DO-AN-02: AppComponents/LCD32/LCD32.h File Reference
LCD32.h File Reference
Driver definitions for 320x240 LCD (16-bit Parallel Interface)
#include "../../AppConfig/All.h"
#include "../../AppUtils/All.h"
#include "../../AppESPWrap/All.h"
#include "../../AppFonts/All.h"
#include "../P16Com/P16Com.h"
#include "LCD32Colors.h"
#include "LCD32Cmds.h"
Classes
struct LCDPoint_t
Point structure for polygon drawing.
struct LCD32Dev_t
LCD Device Structure.
Macros
#define LCD32_LOG_SECTION
#define LCD32_UTILS_SECTION
#define LCD32_THREAD_SAFE_EN 1
#define LCD32_CANVAS_IN_PSRAM_EN 1
Use PSRAM to store the canvas (buffer)
#define LCD32_LOG_EN 1
Enable standard logging for this module.
#define LCD32_LOG1_EN 1
Enable verbose/detailed logging.
#define LCD32_ERR_EN 1
Enable error logging.
#define LCD32_LOG_ENTRY 1
Enable function entry tracing.
#define LCD32_LOG_EXIT 1
Enable function exit tracing.
#define LCD32_ORIENTATION_PORTRAIT 0
Screen Orientation Options.
#define LCD32_ORIENTATION_LANDSCAPE 1
320x240
#define LCD32_ORIENTATION_PORTRAIT_FLIP 2
240x320, Flipped
#define LCD32_ORIENTATION_LANDSCAPE_FLIP 3
320x240, Flipped
#define LCD32_NATIVE_W 240
#define LCD32_NATIVE_H 320
#define LCD32_DEFAULT_ORIENTATION LCD32_ORIENTATION_LANDSCAPE
#define LCD32_DEFAULT_COLOR_BIT sizeof(Color_t)
#define LCD32Log(...)
#define LCD32Err(...)
#define LCD32Exit(...)
#define LCD32ReturnWithLog(ret, ...)
#define LCD32Entry(...)
#define LCD32Log1(...)
#define LCD32SetHighBrightLightPin(lcdDev)
LCD32_LOG_SECTION.
#define LCD32SetLowBrightLightPin(lcdDev)
Turn ON Backlight.
#define LCD32SetDataTransaction(dev)
Macros for Transaction Management.
#define LCD32SetCommandTransaction(dev)
#define LCD32StartTransaction(dev)
#define LCD32StopTransaction(dev)
Typedefs
typedef int16_t Dim_t
Dimension type for LCD.
typedef uint16_t Color_t
16-bit color type for LCD
typedef struct LCD32Dev_t LCD32Dev_t
LCD Device Structure.
Enumerations
enum LCD320x240PositiveStatusFlag_e { __P16COM_RESERVED = 0x00000001 , LCD32_INITIALIZED = 0x00000002 }
Predefined colors.
Functions
LCD32Dev_t * LCD32New ()
Allocates memory for a new LCD32Dev_t object and Canvas.
void LCD32Delete (LCD32Dev_t *Dev)
Deallocate memory for LCD32Dev_t object and Canvas.
DefaultRet_t LCD32Config (LCD32Dev_t *Dev, const Pin_t *CtlPins, const Pin_t *DatPins)
Configure pin mapping for LCD.
DefaultRet_t LCD32Init (LCD32Dev_t *Dev)
Initialize the LCD (GPIOs, Reset, Startup Sequence)
DefaultRet_t LCD32ReConfig (LCD32Dev_t *Dev)
Re-run configuration logic.
void LCD32SetAddressWindow (LCD32Dev_t *Dev, Dim_t x, Dim_t y, Dim_t w, Dim_t h)
Set the active drawing area window on the LCD.
void LCD32FlushCanvas (LCD32Dev_t *Dev)
Flush the internal Canvas buffer to the display.
void LCD32FillCanvas (LCD32Dev_t *Dev, Color_t Color)
Fill the entire canvas with a single color.
void LCD32SetCanvasPixel (LCD32Dev_t *Dev, Dim_t Row, Dim_t Col, Color_t Color)
Draw a single pixel on the canvas (with bounds check)
void LCD32DirectlyWritePixel (LCD32Dev_t *Dev, Dim_t Row, Dim_t Col, Color_t Color)
Write a single pixel directly to the LCD (bypassing canvas)
DefaultRet_t LCD32DrawLine (LCD32Dev_t *Dev, Dim_t r0, Dim_t c0, Dim_t r1, Dim_t c1, Color_t Color)
Draw a line using Bresenham's algorithm.
DefaultRet_t LCD32DrawThickLine (LCD32Dev_t *Dev, Dim_t r0, Dim_t c0, Dim_t r1, Dim_t c1, Color_t Color, Dim_t Thickness)
Draw a thick line.
DefaultRet_t LCD32DrawEmptyRect (LCD32Dev_t *Dev, Dim_t rTopLeft, Dim_t cTopLeft, Dim_t rBottomRight, Dim_t cBottomRight, Dim_t EdgeSize, Color_t Color)
Draw an empty rectangle.
DefaultRet_t LCD32DrawPolygon (LCD32Dev_t *Dev, const LCDPoint_t *Points, size_t N, Color_t Color)
Draw a polygon outline.
DefaultRet_t LCD32DrawFilledPolygon (LCD32Dev_t *Dev, const LCDPoint_t *Points, size_t N, Color_t Color)
Draw a filled polygon (Scanline algorithm)
DefaultRet_t LCD32DrawChar (LCD32Dev_t *Dev, Dim_t r, Dim_t c, char Ch, const GFXfont *Font, Color_t Color)
Draw a character using GFX font.
DefaultRet_t LCD32DrawText (LCD32Dev_t *Dev, Dim_t r, Dim_t c, const char *Str, const GFXfont *Font, Color_t Color)
Draw a string using GFX font.
void LCD32WriteCmd (LCD32Dev_t *Dev, uint16_t Cmd)
Write a command byte to the LCD.
void LCD32WriteData (LCD32Dev_t *Dev, uint16_t Data)
Write a data byte/word to the LCD.
Detailed Description
Driver definitions for 320x240 LCD (16-bit Parallel Interface)
Extends P16Dev_t driver with specific LCD control pins (Backlight).
Author
Nguyen Thanh Phu
Definition in file LCD32.h.
Macro Definition Documentation
LCD32_CANVAS_IN_PSRAM_EN
#define LCD32_CANVAS_IN_PSRAM_EN 1
Use PSRAM to store the canvas (buffer)
Definition at line 34 of file LCD32.h.
LCD32_DEFAULT_COLOR_BIT
#define LCD32_DEFAULT_COLOR_BIT sizeof(Color_t)
Definition at line 62 of file LCD32.h.
LCD32_DEFAULT_ORIENTATION
#define LCD32_DEFAULT_ORIENTATION LCD32_ORIENTATION_LANDSCAPE
Definition at line 61 of file LCD32.h.
Referenced by LCD32New().
LCD32_ERR_EN
#define LCD32_ERR_EN 1
Enable error logging.
Definition at line 41 of file LCD32.h.
LCD32_LOG1_EN
#define LCD32_LOG1_EN 1
Enable verbose/detailed logging.
Definition at line 39 of file LCD32.h.
LCD32_LOG_EN
#define LCD32_LOG_EN 1
Enable standard logging for this module.
Definition at line 37 of file LCD32.h.
LCD32_LOG_ENTRY
#define LCD32_LOG_ENTRY 1
Enable function entry tracing.
Definition at line 43 of file LCD32.h.
LCD32_LOG_EXIT
#define LCD32_LOG_EXIT 1
Enable function exit tracing.
Definition at line 45 of file LCD32.h.
LCD32_LOG_SECTION
#define LCD32_LOG_SECTION
Definition at line 28 of file LCD32.h.
LCD32_NATIVE_H
#define LCD32_NATIVE_H 320
Definition at line 59 of file LCD32.h.
Referenced by LCD32Init(), and LCD32New().
LCD32_NATIVE_W
#define LCD32_NATIVE_W 240
Definition at line 58 of file LCD32.h.
Referenced by LCD32Init(), and LCD32New().
LCD32_ORIENTATION_LANDSCAPE
#define LCD32_ORIENTATION_LANDSCAPE 1
320x240
Definition at line 54 of file LCD32.h.
Referenced by LCD32Init().
LCD32_ORIENTATION_LANDSCAPE_FLIP
#define LCD32_ORIENTATION_LANDSCAPE_FLIP 3
320x240, Flipped
Definition at line 56 of file LCD32.h.
Referenced by LCD32Init().
LCD32_ORIENTATION_PORTRAIT
#define LCD32_ORIENTATION_PORTRAIT 0
Screen Orientation Options.
240x320
Definition at line 53 of file LCD32.h.
Referenced by LCD32Init().
LCD32_ORIENTATION_PORTRAIT_FLIP
#define LCD32_ORIENTATION_PORTRAIT_FLIP 2
240x320, Flipped
Definition at line 55 of file LCD32.h.
Referenced by LCD32Init().
LCD32_THREAD_SAFE_EN
#define LCD32_THREAD_SAFE_EN 1
Definition at line 31 of file LCD32.h.
LCD32_UTILS_SECTION
#define LCD32_UTILS_SECTION
Definition at line 29 of file LCD32.h.
LCD32Entry
#define LCD32Entry (...)
Definition at line 282 of file LCD32.h.
Referenced by LCD32Config(), LCD32Init(), and LCD32ReConfig().
LCD32Err
#define LCD32Err (...)
Definition at line 264 of file LCD32.h.
Referenced by LCD32Config(), LCD32DirectlyWritePixel(), LCD32FlushCanvas(), LCD32Init(), and LCD32New().
LCD32Exit
#define LCD32Exit (...)
Definition at line 274 of file LCD32.h.
LCD32Log
#define LCD32Log (...)
Definition at line 257 of file LCD32.h.
Referenced by LCD32Init(), and LCD32New().
LCD32Log1
#define LCD32Log1 (...)
Definition at line 289 of file LCD32.h.
LCD32ReturnWithLog
#define LCD32ReturnWithLog (ret, ...)
Value:
return ret;
Definition at line 275 of file LCD32.h.
Referenced by LCD32Config(), and LCD32Init().
LCD32SetCommandTransaction
#define LCD32SetCommandTransaction (dev)
Value:
P16SetLowRegSelPin((&(dev->P16Com)))
Definition at line 304 of file LCD32.h.
Referenced by LCD32WriteCmd().
LCD32SetDataTransaction
#define LCD32SetDataTransaction (dev)
Value:
P16SetHighRegSelPin((&(dev->P16Com)))
Macros for Transaction Management.
Definition at line 303 of file LCD32.h.
Referenced by LCD32DirectlyWritePixel(), LCD32FlushCanvas(), LCD32Init(), and LCD32WriteData().
LCD32SetHighBrightLightPin
#define LCD32SetHighBrightLightPin (lcdDev)
Value:
IOSet(1ULL << (lcdDev)->BrightLight)
LCD32_LOG_SECTION.
Turn OFF Backlight (Active Low logic assumed for P-Channel/PNP, check HW!)
Definition at line 297 of file LCD32.h.
Referenced by LCD32Init().
LCD32SetLowBrightLightPin
#define LCD32SetLowBrightLightPin (lcdDev)
Value:
IOClr(1ULL << (lcdDev)->BrightLight)
Turn ON Backlight.
Definition at line 300 of file LCD32.h.
LCD32StartTransaction
#define LCD32StartTransaction (dev)
Value:
P16SetLowChipSelPin((&(dev->P16Com)))
Definition at line 305 of file LCD32.h.
Referenced by LCD32DirectlyWritePixel(), LCD32FlushCanvas(), LCD32Init(), and LCD32SetAddressWindow().
LCD32StopTransaction
#define LCD32StopTransaction (dev)
Value:
P16SetHighChipSelPin((&(dev->P16Com)))
Definition at line 306 of file LCD32.h.
Referenced by LCD32DirectlyWritePixel(), LCD32FlushCanvas(), LCD32Init(), and LCD32SetAddressWindow().
Typedef Documentation
Color_t
typedef uint16_t Color_t
16-bit color type for LCD
Definition at line 50 of file LCD32.h.
Dim_t
typedef int16_t Dim_t
Dimension type for LCD.
Definition at line 48 of file LCD32.h.
LCD32Dev_t
typedef struct LCD32Dev_t LCD32Dev_t
LCD Device Structure.
Implements memory overlay to extend P16Dev_t without breaking compatibility.
Enumeration Type Documentation
LCD320x240PositiveStatusFlag_e
enum LCD320x240PositiveStatusFlag_e
Predefined colors.
Datasheet commands
Status flags for the driver
Enumerator
__P16COM_RESERVED
Reserved for P16Com compatibility.
LCD32_INITIALIZED
Driver is initialized and ready.
Definition at line 70 of file LCD32.h.
{
    __P16COM_RESERVED               = 0x00000001,
    LCD32_INITIALIZED               = 0x00000002,
};
Function Documentation
LCD32Config()
DefaultRet_t LCD32Config (LCD32Dev_t * Dev, const Pin_t * CtlPins, const Pin_t * DatPins)
Configure pin mapping for LCD.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
CtlPins (const Pin_t *) Array of 6 pins: [RD, WR, CS, RS, RST, BL]
DatPins (const Pin_t *) Array of 16 pins: [D0..D15]
Returns
STAT_OKE or Error Code
Extract BrightLight (Index 5 in User Array) User array expected: [RD, WR, CS, RS, RST, BL]
Config Control Pins (First 5)
Config Data Pins (16)
Definition at line 90 of file LCD32.c.
{
    LCD32Entry("LCD32Config(%p, %p, %p)", Dev, CtlPins, DatPins);
    if(IsNull(Dev) || IsNull(CtlPins) || IsNull(DatPins)){
        LCD32ReturnWithLog(STAT_ERR_NULL, "LCD32Config() : STAT_ERR_NULL");
    }
    if(IsStandardPin(CtlPins[5])){
        Dev->BrightLight = CtlPins[5];
    } else {
        LCD32Err("[LCD32Config] Invalid BrightLight Pin");
        LCD32ReturnWithLog(STAT_ERR_INVALID_ARG, "LCD32Config() : STAT_ERR_INVALID_ARG");
    }
    DefaultRet_t ret = P16ComConfigCtl(&(Dev->P16Com), CtlPins);
    if(ret != STAT_OKE){
        LCD32ReturnWithLog(ret, "LCD32Config() : Error");
    }
    ret = P16ComConfigDat(&(Dev->P16Com), DatPins);
    if(ret != STAT_OKE){
        LCD32ReturnWithLog(ret, "LCD32Config() : Error");
    }
    LCD32ReturnWithLog(STAT_OKE, "LCD32Config() : STAT_OKE");
}
References LCD32Dev_t::BrightLight, IsNull, IsStandardPin, LCD32Entry, LCD32Err, LCD32ReturnWithLog, LCD32Dev_t::P16Com, P16ComConfigCtl(), P16ComConfigDat(), STAT_ERR_INVALID_ARG, STAT_ERR_NULL, and STAT_OKE.
Referenced by TaskScreen().
LCD32Delete()
void LCD32Delete (LCD32Dev_t * Dev)
Deallocate memory for LCD32Dev_t object and Canvas.
Parameters
Dev (LCD32Dev_t *) Pointer to the LCD32Dev_t object to be deleted
Definition at line 75 of file LCD32.c.
{
    if(Dev != NULL){
        if(Dev->Canvas != NULL){
            free(Dev->Canvas);
        }
        #if (LCD32_THREAD_SAFE_EN == 1)
            if (Dev->mutex) {
                vSemaphoreDelete(Dev->mutex);
            }
        #endif
        free(Dev);
    }
}
References LCD32Dev_t::Canvas.
Referenced by TaskScreen().
LCD32DirectlyWritePixel()
void LCD32DirectlyWritePixel (LCD32Dev_t * Dev, Dim_t Row, Dim_t Col, Color_t Color)
Write a single pixel directly to the LCD (bypassing canvas)
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Row (Dim_t) The row (y-coordinate) of the pixel
Col (Dim_t) The column (x-coordinate) of the pixel
Color (Color_t) The color of the pixel
Definition at line 428 of file LCD32.c.
{
    if (Row >= 0 && Row < Dev->Height && Col >= 0 && Col < Dev->Width) {
        #if (LCD32_THREAD_SAFE_EN == 1)
        if (xSemaphoreTake(Dev->mutex, portMAX_DELAY) != pdTRUE) {
            LCD32Err("[LCD32DirectlyWritePixel] Failed to take mutex");
            return;
        }
        #endif
        LCD32SetAddressWindow(Dev, Col, Row, 1, 1); // Note: AddressWindow usually takes x, y (Col, Row)
        LCD32StartTransaction(Dev);
        LCD32SetDataTransaction(Dev);
        P16ComWrite(&(Dev->P16Com), Color);
        LCD32StopTransaction(Dev);
        #if (LCD32_THREAD_SAFE_EN == 1)
        xSemaphoreGive(Dev->mutex);
        #endif
    }
}
References LCD32Err, LCD32SetAddressWindow(), LCD32SetDataTransaction, LCD32StartTransaction, LCD32StopTransaction, LCD32Dev_t::P16Com, and P16ComWrite().
LCD32DrawChar()
DefaultRet_t LCD32DrawChar (LCD32Dev_t * Dev, Dim_t r, Dim_t c, char Ch, const GFXfont * Font, Color_t Color)
Draw a character using GFX font.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
r (Dim_t) The top row coordinate for the character
c (Dim_t) The left column coordinate for the character
Ch (char) The character to draw
Font (const GFXfont *) Pointer to the GFX font
Color (Color_t) The color of the character
Definition at line 597 of file LCD32.c.
{
    if (IsNull(Dev) || IsNull(Font)) return STAT_ERR_NULL;
    if (Ch < Font->first || Ch > Font->last) return STAT_ERR_INVALID_ARG;
    GFXglyph *glyph = &Font->glyph[Ch - Font->first];
    uint8_t *bitmap = Font->bitmap;
    uint16_t bo = glyph->bitmapOffset;
    uint8_t  w  = glyph->width, h = glyph->height;
    int8_t   xo = glyph->xOffset, yo = glyph->yOffset;
    uint8_t bits = 0, bitCount = 0;
    for (Dim_t yy = 0; yy < h; yy++) {
        for (Dim_t xx = 0; xx < w; xx++) {
            if (bitCount == 0) {
                bits = bitmap[bo++];
                bitCount = 8;
            }
            if (bits & 0x80) {
                LCD32SetCanvasPixel(Dev, r + yo + yy, c + xo + xx, Color);
            }
            bits <<= 1;
            bitCount--;
        }
    }
    return STAT_OKE;
}
References GFXfont::bitmap, GFXglyph::bitmapOffset, GFXfont::first, GFXfont::glyph, GFXglyph::height, IsNull, GFXfont::last, LCD32SetCanvasPixel(), STAT_ERR_INVALID_ARG, STAT_ERR_NULL, STAT_OKE, GFXglyph::width, GFXglyph::xOffset, and GFXglyph::yOffset.
Referenced by LCD32DrawText().
LCD32DrawEmptyRect()
DefaultRet_t LCD32DrawEmptyRect (LCD32Dev_t * Dev, Dim_t rTopLeft, Dim_t cTopLeft, Dim_t rBottomRight, Dim_t cBottomRight, Dim_t EdgeSize, Color_t Color)
Draw an empty rectangle.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
rTopLeft (Dim_t) The top row of the rectangle
cTopLeft (Dim_t) The left column of the rectangle
rBottomRight (Dim_t) The bottom row of the rectangle
cBottomRight (Dim_t) The right column of the rectangle
EdgeSize (Dim_t) The thickness of the border
Color (Color_t) The color of the border
Definition at line 514 of file LCD32.c.
{
    if (IsNull(Dev)) return STAT_ERR_NULL;
    if (EdgeSize < 1) return STAT_OKE;
    Dim_t width = cBottomRight - cTopLeft + 1;
    Dim_t height = rBottomRight - rTopLeft + 1;
    // Draw 4 filled rectangles for the border
    LCD32DrawFilledRect(Dev, rTopLeft, cTopLeft, EdgeSize, width, Color); // Top
    LCD32DrawFilledRect(Dev, rBottomRight - EdgeSize + 1, cTopLeft, EdgeSize, width, Color); // Bottom
    LCD32DrawFilledRect(Dev, rTopLeft + EdgeSize, cTopLeft, height - 2 * EdgeSize, EdgeSize, Color); // Left
    LCD32DrawFilledRect(Dev, rTopLeft + EdgeSize, cBottomRight - EdgeSize + 1, height - 2 * EdgeSize, EdgeSize, Color); // Right
    return STAT_OKE;
}
References IsNull, LCD32DrawFilledRect(), STAT_ERR_NULL, and STAT_OKE.
LCD32DrawFilledPolygon()
DefaultRet_t LCD32DrawFilledPolygon (LCD32Dev_t * Dev, const LCDPoint_t * Points, size_t N, Color_t Color)
Draw a filled polygon (Scanline algorithm)
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Points (const LCDPoint_t *) Pointer to an array of points (vertices)
N (size_t) The number of points in the array
Color (Color_t) The color to fill the polygon with
Definition at line 546 of file LCD32.c.
{
    if (IsNull(Dev) || IsNull(Points) || N < 3) return STAT_ERR_INVALID_ARG;
    Dim_t minRow = Points[0].row, maxRow = Points[0].row;
    for (size_t i = 1; i < N; i++) {
        if (Points[i].row < minRow) minRow = Points[i].row;
        if (Points[i].row > maxRow) maxRow = Points[i].row;
    }
    if (minRow < 0) minRow = 0;
    if (maxRow >= Dev->Height) maxRow = Dev->Height - 1;
    int32_t interX[128]; // Max 128 intersections
    for (Dim_t y = minRow; y <= maxRow; y++) {
        size_t interCount = 0;
        for (size_t i = 0; i < N; i++) {
            size_t j = (i + 1) % N;
            int32_t x0 = Points[i].col, y0 = Points[i].row;
            int32_t x1 = Points[j].col, y1 = Points[j].row;
            if (y0 == y1) continue; // Horizontal edge
            if (y0 > y1) { // Swap
                int32_t tx = x0; x0 = x1; x1 = tx;
                int32_t ty = y0; y0 = y1; y1 = ty;
            }
            if (y >= y0 && y < y1) {
                // Calculate intersection
                int32_t x = x0 + (int32_t)((int64_t)(x1 - x0) * (y - y0) / (y1 - y0));
                if (interCount < 128) interX[interCount++] = x;
            }
        }
        // Sort intersections using qsort for better performance
        qsort(interX, interCount, sizeof(int32_t), compare_int32);
        // Fill pairs
        for (size_t k = 0; k + 1 < interCount; k += 2) {
            Dim_t xStart = (Dim_t)interX[k];
            Dim_t xEnd = (Dim_t)interX[k+1];
            if (xStart < 0) xStart = 0;
            if (xEnd >= Dev->Width) xEnd = Dev->Width - 1;
            for (Dim_t x = xStart; x <= xEnd; x++) {
                LCD32SetCanvasPixel(Dev, y, x, Color);
            }
        }
    }
    return STAT_OKE;
}
References LCDPoint_t::col, compare_int32(), LCD32Dev_t::Height, IsNull, LCD32SetCanvasPixel(), LCDPoint_t::row, STAT_ERR_INVALID_ARG, STAT_OKE, and LCD32Dev_t::Width.
Referenced by LCD32DrawQuad().
LCD32DrawLine()
DefaultRet_t LCD32DrawLine (LCD32Dev_t * Dev, Dim_t r0, Dim_t c0, Dim_t r1, Dim_t c1, Color_t Color)
Draw a line using Bresenham's algorithm.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
r0 (Dim_t) The starting row (y-coordinate)
c0 (Dim_t) The starting column (x-coordinate)
r1 (Dim_t) The ending row (y-coordinate)
c1 (Dim_t) The ending column (x-coordinate)
Color (Color_t) The color of the line
Definition at line 450 of file LCD32.c.
{
    if (IsNull(Dev)) return STAT_ERR_NULL;
    int16_t dx = abs(c1 - c0), sx = c0 < c1 ? 1 : -1;
    int16_t dy = -abs(r1 - r0), sy = r0 < r1 ? 1 : -1;
    int16_t err = dx + dy, e2;
    while (1) {
        LCD32SetCanvasPixel(Dev, r0, c0, Color);
        if (r0 == r1 && c0 == c1) break;
        e2 = 2 * err;
        if (e2 >= dy) { err += dy; c0 += sx; }
        if (e2 <= dx) { err += dx; r0 += sy; }
    }
    return STAT_OKE;
}
References IsNull, LCD32SetCanvasPixel(), STAT_ERR_NULL, and STAT_OKE.
Referenced by LCD32DrawPolygon(), and LCD32DrawThickLine().
LCD32DrawPolygon()
DefaultRet_t LCD32DrawPolygon (LCD32Dev_t * Dev, const LCDPoint_t * Points, size_t N, Color_t Color)
Draw a polygon outline.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Points (const LCDPoint_t *) Pointer to an array of points (vertices)
N (size_t) The number of points in the array
Color (Color_t) The color of the polygon outline
Definition at line 530 of file LCD32.c.
{
    if (IsNull(Dev) || IsNull(Points) || N < 2) return STAT_ERR_INVALID_ARG;
    for (size_t i = 0; i < N - 1; i++) {
        LCD32DrawLine(Dev, Points[i].row, Points[i].col, Points[i+1].row, Points[i+1].col, Color);
    }
    // Close polygon
    LCD32DrawLine(Dev, Points[N-1].row, Points[N-1].col, Points[0].row, Points[0].col, Color);
    return STAT_OKE;
}
References IsNull, LCD32DrawLine(), STAT_ERR_INVALID_ARG, and STAT_OKE.
LCD32DrawText()
DefaultRet_t LCD32DrawText (LCD32Dev_t * Dev, Dim_t r, Dim_t c, const char * Str, const GFXfont * Font, Color_t Color)
Draw a string using GFX font.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
r (Dim_t) The top row coordinate for the string
c (Dim_t) The left column coordinate for the string
Str (const char *) The null-terminated string to draw
Font (const GFXfont *) Pointer to the GFX font
Color (Color_t) The color of the string
Definition at line 626 of file LCD32.c.
{
    if (IsNull(Dev) || IsNull(Str) || IsNull(Font)) return STAT_ERR_NULL;
    Dim_t cursor_r = r, cursor_c = c;
    while (*Str) {
        char ch = *Str++;
        if (ch == '\n') {
            cursor_c = c;
            cursor_r += Font->yAdvance;
            continue;
        }
        if (ch < Font->first || ch > Font->last) continue;
        GFXglyph *glyph = &Font->glyph[ch - Font->first];
        // Wrap text
        if (cursor_c + glyph->xAdvance >= Dev->Width) {
            cursor_c = c;
            cursor_r += Font->yAdvance;
        }
        LCD32DrawChar(Dev, cursor_r, cursor_c, ch, Font, Color);
        cursor_c += glyph->xAdvance;
    }
    return STAT_OKE;
}
References GFXfont::first, GFXfont::glyph, IsNull, GFXfont::last, LCD32DrawChar(), STAT_ERR_NULL, STAT_OKE, LCD32Dev_t::Width, GFXglyph::xAdvance, and GFXfont::yAdvance.
LCD32DrawThickLine()
DefaultRet_t LCD32DrawThickLine (LCD32Dev_t * Dev, Dim_t r0, Dim_t c0, Dim_t r1, Dim_t c1, Color_t Color, Dim_t Thickness)
Draw a thick line.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
r0 (Dim_t) The starting row (y-coordinate)
c0 (Dim_t) The starting column (x-coordinate)
r1 (Dim_t) The ending row (y-coordinate)
c1 (Dim_t) The ending column (x-coordinate)
Color (Color_t) The color of the line
Thickness (Dim_t) The thickness of the line in pixels
Definition at line 475 of file LCD32.c.
{
    if (IsNull(Dev)) return STAT_ERR_NULL;
    if (Thickness <= 1) return LCD32DrawLine(Dev, r0, c0, r1, c1, Color);
    // Advanced implementation using polygon rendering for sharp corners and flat ends
    int16_t dx = c1 - c0;
    int16_t dy = r1 - r0;
    float len = sqrtf(dx * dx + dy * dy);
    if (len == 0) return STAT_OKE;
    // Calculate the perpendicular vector
    float nx = -dy / len;
    float ny = dx / len;
    float half_thick = (float)Thickness / 2.0f;
    // Calculate the 4 corners of the rectangle representing the thick line
    LCDPoint_t p[4];
    p[0] = (LCDPoint_t){ .row = (Dim_t)roundf(r0 - ny * half_thick), .col = (Dim_t)roundf(c0 - nx * half_thick) };
    p[1] = (LCDPoint_t){ .row = (Dim_t)roundf(r1 - ny * half_thick), .col = (Dim_t)roundf(c1 - nx * half_thick) };
    p[2] = (LCDPoint_t){ .row = (Dim_t)roundf(r1 + ny * half_thick), .col = (Dim_t)roundf(c1 + nx * half_thick) };
    p[3] = (LCDPoint_t){ .row = (Dim_t)roundf(r0 + ny * half_thick), .col = (Dim_t)roundf(c0 + nx * half_thick) };
    // Draw the rectangle (quad)
    LCD32DrawQuad(Dev, p, Color);
    return STAT_OKE;
}
References IsNull, LCD32DrawLine(), LCD32DrawQuad(), STAT_ERR_NULL, and STAT_OKE.
LCD32FillCanvas()
void LCD32FillCanvas (LCD32Dev_t * Dev, Color_t Color)
Fill the entire canvas with a single color.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Color (Color_t) The color to fill the canvas with
Definition at line 412 of file LCD32.c.
{
    if (IsNull(Dev) || IsNull(Dev->Canvas)) return;
    int32_t size = Dev->Width * Dev->Height;
    for (int32_t i = 0; i < size; i++) {
        Dev->Canvas[i] = Color;
    }
}
References LCD32Dev_t::Canvas, LCD32Dev_t::Height, IsNull, and LCD32Dev_t::Width.
Referenced by TaskScreen().
LCD32FlushCanvas()
void LCD32FlushCanvas (LCD32Dev_t * Dev)
Flush the internal Canvas buffer to the display.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Set Address Window to Full Screen
Start Data Stream
Burst Write Pixels using P16Com optimized driver
Definition at line 383 of file LCD32.c.
{
    // LCD32Entry("LCD32FlushCanvas(%p)", Dev);
    if(IsNull(Dev) || IsNull(Dev->Canvas)){
        return;
    }
    #if (LCD32_THREAD_SAFE_EN == 1)
    if (xSemaphoreTake(Dev->mutex, portMAX_DELAY) != pdTRUE) {
        LCD32Err("[LCD32FlushCanvas] Failed to take mutex");
        return;
    }
    #endif
    LCD32SetAddressWindow(Dev, 0, 0, Dev->Width, Dev->Height);
    LCD32StartTransaction(Dev);
    LCD32SetDataTransaction(Dev);
    P16ComWriteArray(&(Dev->P16Com), (P16Data_t *)Dev->Canvas, (Dev->Width * Dev->Height));
    LCD32StopTransaction(Dev);
    #if (LCD32_THREAD_SAFE_EN == 1)
    xSemaphoreGive(Dev->mutex);
    #endif
}
References LCD32Dev_t::Canvas, LCD32Dev_t::Height, IsNull, LCD32Err, LCD32SetAddressWindow(), LCD32SetDataTransaction, LCD32StartTransaction, LCD32StopTransaction, LCD32Dev_t::P16Com, P16ComWriteArray(), and LCD32Dev_t::Width.
Referenced by TaskScreen().
LCD32Init()
DefaultRet_t LCD32Init (LCD32Dev_t * Dev)
Initialize the LCD (GPIOs, Reset, Startup Sequence)
Parameters
Dev (LCD32Dev_t *) Pointer to the LCD32Dev_t object
Returns
STAT_OKE on success
Initialize P16 Bus (GPIOs, Directions)
Initialize BrightLight Pin
Hardware Reset Sequence
Initial Pin States
Turn On Backlight (Active Low logic per macro)
Definition at line 122 of file LCD32.c.
{
    LCD32Entry("LCD32Init(%p)", Dev);
    DefaultRet_t ret;
    P16Dev_t * P16Dev = &(Dev->P16Com);
    ret = P16ComInit(P16Dev);
    if(ret != STAT_OKE){
        LCD32ReturnWithLog(ret, "LCD32Init() : Error");
    }
    if(IsValidPin(Dev->BrightLight)){
        IOConfigAsOutput(Mask64(Dev->BrightLight), -1, -1);
        LCD32SetHighBrightLightPin(Dev); // Turn off/Default state
    }
    P16SetLowResetPin(P16Dev);
    P16BlockingDelay(10000);   // 10ms
    P16SetHighResetPin(P16Dev);
    P16BlockingDelay(120000);  // 120ms wait after reset
    P16SetHighChipSelPin(P16Dev);
    P16SetHighReadPin(P16Dev);
    P16SetHighWritePin(P16Dev);
    // VERIFY DEVICE ID (0xD3 Read ID4)
    LCD32StartTransaction(Dev);
    // Command 0xD3: Read ID4
    LCD32WriteCmd(Dev, 0xD3);
    // Switch to Data Mode (D/CX = 1) for reading parameters
    LCD32SetDataTransaction(Dev);
    // Read Sequence: Dummy -> Dummy (00) -> ID High (93) -> ID Low (41)
    // Note: P16ComRead handles direction switching and strobe logic
    volatile P16Data_t d1 = P16ComRead(P16Dev); // Dummy
    volatile P16Data_t d2 = P16ComRead(P16Dev); // Dummy (Should be 0x00)
    volatile P16Data_t d3 = P16ComRead(P16Dev); // ID High (Should be 0x93)
    volatile P16Data_t d4 = P16ComRead(P16Dev); // ID Low  (Should be 0x41)
    LCD32StopTransaction(Dev);
    uint16_t devId = ((d3 & 0xFF) << 8) | (d4 & 0xFF);
    LCD32Log("[LCD32Init] Read ID: 0x%04X (Raw: %02X %02X %02X %02X)", devId, d1, d2, d3, d4);
    if (devId != 0x9341) {
        LCD32Err("[LCD32Init] Invalid Device ID: 0x%04X (Expected 0x9341)", devId);
        // LCD32ReturnWithLog(STAT_ERR_UNSUPPORTED, "LCD32Init() : Wrong Device ID");
        // Uncomment above line to enforce check, currently just logging error for debugging
    }
    // Set MADCTL based on orientation and update Width/Height
    uint16_t madctl_val = 0;
    switch (Dev->Orientation) {
        case LCD32_ORIENTATION_PORTRAIT:
            madctl_val = (MADCTL_MX | MADCTL_BGR); // 0x48
            Dev->Width = LCD32_NATIVE_W;
            Dev->Height = LCD32_NATIVE_H;
            break;
        case LCD32_ORIENTATION_LANDSCAPE:
            madctl_val = (MADCTL_MV | MADCTL_BGR); // 0x28
            Dev->Width = LCD32_NATIVE_H;
            Dev->Height = LCD32_NATIVE_W;
            break;
        case LCD32_ORIENTATION_PORTRAIT_FLIP:
            madctl_val = (MADCTL_MY | MADCTL_BGR); // 0x88
            Dev->Width = LCD32_NATIVE_W;
            Dev->Height = LCD32_NATIVE_H;
            break;
        case LCD32_ORIENTATION_LANDSCAPE_FLIP:
            madctl_val = (MADCTL_MY | MADCTL_MX | MADCTL_MV | MADCTL_BGR); // 0xE8
            Dev->Width = LCD32_NATIVE_H;
            Dev->Height = LCD32_NATIVE_W;
            break;
        default: // Default to landscape as it's most common for these displays
            madctl_val = (MADCTL_MV | MADCTL_BGR); // 0x28
            Dev->Width = LCD32_NATIVE_H;
            Dev->Height = LCD32_NATIVE_W;
            Dev->Orientation = LCD32_ORIENTATION_LANDSCAPE; // Correct the state
            break;
    }
    LCD32Log("[LCD32Init] Orientation: %d, W: %d, H: %d, MADCTL: 0x%02X", Dev->Orientation, Dev->Width, Dev->Height, madctl_val);
    // ILI9341 INITIALIZATION SEQUENCE
    LCD32StartTransaction(Dev);
    // Power Control A
    LCD32WriteCmd(Dev, ILI9341_POWER_CONTROL_A);
    LCD32WriteData(Dev, 0x39);
    LCD32WriteData(Dev, 0x2C);
    LCD32WriteData(Dev, 0x00);
    LCD32WriteData(Dev, 0x34);
    LCD32WriteData(Dev, 0x02);
    // Power Control B
    LCD32WriteCmd(Dev, ILI9341_POWER_CONTROL_B);
    LCD32WriteData(Dev, 0x00);
    LCD32WriteData(Dev, 0xC1);
    LCD32WriteData(Dev, 0x30);
    // Driver Timing Control A
    LCD32WriteCmd(Dev, ILI9341_DRIVER_TIMING_CTRL_A_INT);
    LCD32WriteData(Dev, 0x85);
    LCD32WriteData(Dev, 0x00);
    LCD32WriteData(Dev, 0x78);
    // Driver Timing Control B
    LCD32WriteCmd(Dev, ILI9341_DRIVER_TIMING_CTRL_B);
    LCD32WriteData(Dev, 0x00);
    LCD32WriteData(Dev, 0x00);
    // Power On Sequence Control
    LCD32WriteCmd(Dev, ILI9341_POWER_ON_SEQ_CTRL);
    LCD32WriteData(Dev, 0x64);
    LCD32WriteData(Dev, 0x03);
    LCD32WriteData(Dev, 0x12);
    LCD32WriteData(Dev, 0x81);
    // Pump Ratio Control
    LCD32WriteCmd(Dev, ILI9341_PUMP_RATIO_CONTROL);
    LCD32WriteData(Dev, 0x20);
    // Power Control 1
    LCD32WriteCmd(Dev, ILI9341_POWER_CONTROL_1);
    LCD32WriteData(Dev, 0x23);
    // Power Control 2
    LCD32WriteCmd(Dev, ILI9341_POWER_CONTROL_2);
    LCD32WriteData(Dev, 0x10);
    // VCOM Control 1
    LCD32WriteCmd(Dev, ILI9341_VCOM_CONTROL_1);
    LCD32WriteData(Dev, 0x3e);
    LCD32WriteData(Dev, 0x28);
    // VCOM Control 2
    LCD32WriteCmd(Dev, ILI9341_VCOM_CONTROL_2);
    LCD32WriteData(Dev, 0x86);
    // Memory Access Control
    LCD32WriteCmd(Dev, ILI9341_MEMORY_ACCESS_CONTROL);
    LCD32WriteData(Dev, madctl_val);
    // Pixel Format Set
    LCD32WriteCmd(Dev, ILI9341_PIXEL_FORMAT_SET);
    LCD32WriteData(Dev, 0x55); // 16-bit
    // Frame Rate Control
    LCD32WriteCmd(Dev, ILI9341_FRAME_RATE_NORMAL);
    LCD32WriteData(Dev, 0x00);
    LCD32WriteData(Dev, 0x18);
    // Display Function Control
    LCD32WriteCmd(Dev, ILI9341_DISPLAY_FUNCTION_CTRL);
    LCD32WriteData(Dev, 0x08);
    LCD32WriteData(Dev, 0x82);
    LCD32WriteData(Dev, 0x27);
    // 3G Gamma
    LCD32WriteCmd(Dev, ILI9341_ENABLE_3G);
    LCD32WriteData(Dev, 0x00);
    // Gamma Set
    LCD32WriteCmd(Dev, ILI9341_GAMMA_SET);
    LCD32WriteData(Dev, 0x01);
    // Positive Gamma Correction
    LCD32WriteCmd(Dev, ILI9341_POSITIVE_GAMMA_CORR);
    LCD32WriteData(Dev, 0x0F); LCD32WriteData(Dev, 0x31);
    LCD32WriteData(Dev, 0x2B); LCD32WriteData(Dev, 0x0C);
    LCD32WriteData(Dev, 0x0E); LCD32WriteData(Dev, 0x08);
    LCD32WriteData(Dev, 0x4E); LCD32WriteData(Dev, 0xF1);
    LCD32WriteData(Dev, 0x37); LCD32WriteData(Dev, 0x07);
    LCD32WriteData(Dev, 0x10); LCD32WriteData(Dev, 0x03);
    LCD32WriteData(Dev, 0x0E); LCD32WriteData(Dev, 0x09);
    LCD32WriteData(Dev, 0x00);
    // Negative Gamma Correction
    LCD32WriteCmd(Dev, ILI9341_NEGATIVE_GAMMA_CORR);
    LCD32WriteData(Dev, 0x00); LCD32WriteData(Dev, 0x0E);
    LCD32WriteData(Dev, 0x14); LCD32WriteData(Dev, 0x03);
    LCD32WriteData(Dev, 0x11); LCD32WriteData(Dev, 0x07);
    LCD32WriteData(Dev, 0x31); LCD32WriteData(Dev, 0xC1);
    LCD32WriteData(Dev, 0x48); LCD32WriteData(Dev, 0x08);
    LCD32WriteData(Dev, 0x0F); LCD32WriteData(Dev, 0x0C);
    LCD32WriteData(Dev, 0x31); LCD32WriteData(Dev, 0x36);
    LCD32WriteData(Dev, 0x0F);
    // Sleep Out
    LCD32WriteCmd(Dev, ILI9341_SLEEP_OUT);
    P16BlockingDelay(120000);
    // Display On
    LCD32WriteCmd(Dev, ILI9341_DISPLAY_ON);
    P16BlockingDelay(50000); // Add delay for stability
    LCD32StopTransaction(Dev);
    // LCD32SetLowBrightLightPin(Dev); // Original line (Assumes Active-Low)
    LCD32SetHighBrightLightPin(Dev);   // TEST: Try this for Active-High backlight
    LCD32Log("[LCD32Init] Backlight turned ON.");
    Dev->StatusFlag |= LCD32_INITIALIZED;
    LCD32ReturnWithLog(STAT_OKE, "LCD32Init() : STAT_OKE");
}
References LCD32Dev_t::BrightLight, LCD32Dev_t::Height, ILI9341_DISPLAY_FUNCTION_CTRL, ILI9341_DISPLAY_ON, ILI9341_DRIVER_TIMING_CTRL_A_INT, ILI9341_DRIVER_TIMING_CTRL_B, ILI9341_ENABLE_3G, ILI9341_FRAME_RATE_NORMAL, ILI9341_GAMMA_SET, ILI9341_MEMORY_ACCESS_CONTROL, ILI9341_NEGATIVE_GAMMA_CORR, ILI9341_PIXEL_FORMAT_SET, ILI9341_POSITIVE_GAMMA_CORR, ILI9341_POWER_CONTROL_1, ILI9341_POWER_CONTROL_2, ILI9341_POWER_CONTROL_A, ILI9341_POWER_CONTROL_B, ILI9341_POWER_ON_SEQ_CTRL, ILI9341_PUMP_RATIO_CONTROL, ILI9341_SLEEP_OUT, ILI9341_VCOM_CONTROL_1, ILI9341_VCOM_CONTROL_2, IOConfigAsOutput(), IsValidPin, LCD32_INITIALIZED, LCD32_NATIVE_H, LCD32_NATIVE_W, LCD32_ORIENTATION_LANDSCAPE, LCD32_ORIENTATION_LANDSCAPE_FLIP, LCD32_ORIENTATION_PORTRAIT, LCD32_ORIENTATION_PORTRAIT_FLIP, LCD32Entry, LCD32Err, LCD32Log, LCD32ReturnWithLog, LCD32SetDataTransaction, LCD32SetHighBrightLightPin, LCD32StartTransaction, LCD32StopTransaction, LCD32WriteCmd(), LCD32WriteData(), MADCTL_BGR, MADCTL_MV, MADCTL_MX, MADCTL_MY, Mask64, LCD32Dev_t::Orientation, P16BlockingDelay, LCD32Dev_t::P16Com, P16ComInit(), P16ComRead(), P16SetHighChipSelPin, P16SetHighReadPin, P16SetHighResetPin, P16SetHighWritePin, P16SetLowResetPin, STAT_OKE, LCD32Dev_t::StatusFlag, and LCD32Dev_t::Width.
Referenced by LCD32ReConfig(), and TaskScreen().
LCD32New()
LCD32Dev_t * LCD32New ()
Allocates memory for a new LCD32Dev_t object and Canvas.
Returns
Pointer to the new object or NULL if malloc fails
Reset P16Com part (Initialize internal arrays to -1)
Preset internal P16Com flags/masks
Preset LCD specific fields
Allocate Canvas
Allocate in DRAM
Clear Canvas (Black)
Definition at line 10 of file LCD32.c.
                       {
    LCD32Dev_t * DevPtr = (LCD32Dev_t *) malloc(sizeof(LCD32Dev_t));
    if(IsNull(DevPtr)){
        LCD32Err("[LCD32New] Malloc failed for Struct");
        return NULL;
    }
    REPN(i, P16COM_DAT_PIN_NUM_W_PADDING){
        (DevPtr->P16Com).DatPinArr[i] = -1;
    }
    REPN(i, P16COM_CTL_PIN_NUM_W_PADDING){
        (DevPtr->P16Com).CtlPinArr[i] = -1;
    }
    (DevPtr->P16Com).StatusFlag = 0;
    (DevPtr->P16Com).CtlIOMask = 0;
    (DevPtr->P16Com).DatIOMask = 0;
    DevPtr->BrightLight = -1;
    DevPtr->Orientation = LCD32_DEFAULT_ORIENTATION;
    // Width and Height will be set properly in LCD32Init based on orientation
    DevPtr->Width       = 0;
    DevPtr->Height      = 0;
    #if (LCD32_THREAD_SAFE_EN == 1)
        DevPtr->mutex = xSemaphoreCreateMutex();
        if (IsNull(DevPtr->mutex)) {
            LCD32Err("[LCD32New] Failed to create mutex");
            free(DevPtr);
            return NULL;
        }
    #endif
    #if (LCD32_CANVAS_IN_PSRAM_EN == 1)
        DevPtr->Canvas = (Color_t *)heap_caps_malloc(sizeof(Color_t) * LCD32_NATIVE_W * LCD32_NATIVE_H, MALLOC_CAP_SPIRAM);
    #else
        DevPtr->Canvas = (Color_t *)malloc(sizeof(Color_t) * LCD32_NATIVE_W * LCD32_NATIVE_H);
    #endif
    if(IsNull(DevPtr->Canvas)){
        LCD32Err("[LCD32New] Malloc failed for Canvas");
        #if (LCD32_THREAD_SAFE_EN == 1)
            if (DevPtr->mutex) vSemaphoreDelete(DevPtr->mutex);
        #endif
        free(DevPtr);
        return NULL;
    }
    for(int32_t i = 0; i < (LCD32_NATIVE_W * LCD32_NATIVE_H); i++){
        (DevPtr->Canvas)[i] = COLOR_BLACK;
    }
    LCD32Log("[LCD32New] Created %p (Canvas @ %p)", DevPtr, DevPtr->Canvas);
    return DevPtr;
}
References LCD32Dev_t::BrightLight, LCD32Dev_t::Canvas, COLOR_BLACK, LCD32Dev_t::Height, IsNull, LCD32_DEFAULT_ORIENTATION, LCD32_NATIVE_H, LCD32_NATIVE_W, LCD32Err, LCD32Log, LCD32Dev_t::Orientation, LCD32Dev_t::P16Com, P16COM_CTL_PIN_NUM_W_PADDING, P16COM_DAT_PIN_NUM_W_PADDING, REPN, and LCD32Dev_t::Width.
Referenced by TaskScreen().
LCD32ReConfig()
DefaultRet_t LCD32ReConfig (LCD32Dev_t * Dev)
Re-run configuration logic.
Parameters
Dev (LCD32Dev_t *) Pointer to the LCD32Dev_t object
Returns
STAT_OKE on success
Definition at line 339 of file LCD32.c.
{
    LCD32Entry("LCD32ReConfig(%p)", Dev);
    return LCD32Init(Dev);
}
References LCD32Entry, and LCD32Init().
LCD32SetAddressWindow()
void LCD32SetAddressWindow (LCD32Dev_t * Dev, Dim_t x, Dim_t y, Dim_t w, Dim_t h)
Set the active drawing area window on the LCD.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
x (Dim_t) The starting column (x-coordinate)
y (Dim_t) The starting row (y-coordinate)
w (Dim_t) The width of the window
h (Dim_t) The height of the window
Definition at line 359 of file LCD32.c.
{
    LCD32StartTransaction(Dev);
    // Column Address Set
    LCD32WriteCmd(Dev, ILI9341_COLUMN_ADDRESS_SET);
    LCD32WriteData(Dev, x >> 8);
    LCD32WriteData(Dev, x & 0xFF);
    LCD32WriteData(Dev, (x + w - 1) >> 8);
    LCD32WriteData(Dev, (x + w - 1) & 0xFF);
    // Page Address Set
    LCD32WriteCmd(Dev, ILI9341_PAGE_ADDRESS_SET);
    LCD32WriteData(Dev, y >> 8);
    LCD32WriteData(Dev, y & 0xFF);
    LCD32WriteData(Dev, (y + h - 1) >> 8);
    LCD32WriteData(Dev, (y + h - 1) & 0xFF);
    // Memory Write
    LCD32WriteCmd(Dev, ILI9341_MEMORY_WRITE);
    LCD32StopTransaction(Dev);
}
References ILI9341_COLUMN_ADDRESS_SET, ILI9341_MEMORY_WRITE, ILI9341_PAGE_ADDRESS_SET, LCD32StartTransaction, LCD32StopTransaction, LCD32WriteCmd(), and LCD32WriteData().
Referenced by LCD32DirectlyWritePixel(), and LCD32FlushCanvas().
LCD32SetCanvasPixel()
void LCD32SetCanvasPixel (LCD32Dev_t * Dev, Dim_t Row, Dim_t Col, Color_t Color)
Draw a single pixel on the canvas (with bounds check)
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Row (Dim_t) The row (y-coordinate) of the pixel
Col (Dim_t) The column (x-coordinate) of the pixel
Color (Color_t) The color of the pixel
Definition at line 421 of file LCD32.c.
{
    if (Row >= 0 && Row < Dev->Height && Col >= 0 && Col < Dev->Width) {
        Dev->Canvas[Row * Dev->Width + Col] = Color;
    }
}
References LCD32Dev_t::Canvas, and LCD32Dev_t::Width.
Referenced by LCD32DrawChar(), LCD32DrawFilledPolygon(), LCD32DrawFilledRect(), and LCD32DrawLine().
LCD32WriteCmd()
void LCD32WriteCmd (LCD32Dev_t * Dev, uint16_t Cmd)
Write a command byte to the LCD.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Cmd (uint16_t) The command to write
Write a command byte to the LCD.
Definition at line 345 of file LCD32.c.
{
    P16Log1("LCD32WriteCmd(%p, 0x%X)", Dev, Cmd);
    LCD32SetCommandTransaction(Dev);
    P16ComWrite(&(Dev->P16Com), Cmd);
}
References LCD32SetCommandTransaction, LCD32Dev_t::P16Com, P16ComWrite(), and P16Log1.
Referenced by LCD32Init(), and LCD32SetAddressWindow().
LCD32WriteData()
void LCD32WriteData (LCD32Dev_t * Dev, uint16_t Data)
Write a data byte/word to the LCD.
Parameters
Dev (LCD32Dev_t *) Pointer to the device object
Data (uint16_t) The data to write
Write a data byte/word to the LCD.
Definition at line 352 of file LCD32.c.
{
    P16Log1("LCD32WriteData(%p, 0x%X)", Dev, Data);
    LCD32SetDataTransaction(Dev);
    P16ComWrite(&(Dev->P16Com), Data);
}
References LCD32SetDataTransaction, LCD32Dev_t::P16Com, P16ComWrite(), and P16Log1.
Referenced by LCD32Init(), and LCD32SetAddressWindow().