DO-AN-02: main/monitor.h File Reference
monitor.h File Reference
Monitor & Display Logic; Handles LCD initialization, rendering loop, and visualization demos (Oscilloscope/Charts).
#include "../helper/general.h"
#include "../comDriver/lcd32/lcd32.h"
#include "ui.h"
Macros
#define IS_SYSTEM_INIT (systemStage == SYSTEM_INIT)
LOCAL HELPER //////////////////////////////////////////////////////////////////////////////////.
#define IS_SYSTEM_RUNNING (systemStage == SYSTEM_RUNNING)
#define IS_SYSTEM_STOPPED (systemStage == SYSTEM_STOPPED)
#define ADD_NEW_TASK_TO_CPU0(tagName, taskFunc, taskName, stackSize, params, priority, taskHandle)
#define ADD_NEW_TASK_TO_CPU1(tagName, taskFunc, taskName, stackSize, params, priority, taskHandle)
#define WAIT_SYSTEM_INIT_COMPLETED() while (IS_SYSTEM_INIT) { vTaskDelay(1); }
Enumerations
enum ENUM_SYSTEM_STAGE { SYSTEM_INIT = 0 , SYSTEM_RUNNING = 1 , SYSTEM_STOPPED = 2 , SYSTEM_STAGE_COUNT }
DEFINITIONS ///////////////////////////////////////////////////////////////////////////////////.
enum ENUM_SYSTEM_MODE { SYSTEM_MODE_DEMO_OSC_CAP = 0 , SYSTEM_MODE_DEMO_SPI_CAP = 1 , SYSTEM_MODE_DEMO_I2C_CAP = 2 , SYSTEM_MODE_COUNT }
SYSTEM MODE ///////////////////////////////////////////////////////////////////////////////////.
Functions
void systemInit ()
TASKS /////////////////////////////////////////////////////////////////////////////////////////.
Variables
volatile flag_t systemStage = SYSTEM_INIT
volatile portMUX_TYPE systemStageMutex = portMUX_INITIALIZER_UNLOCKED
Mutex for synchronizing access to the system stage flag.
static const char * SYSTEM_MODE_STR []
volatile flag_t systemMode = SYSTEM_MODE_DEMO_OSC_CAP
Detailed Description
Monitor & Display Logic; Handles LCD initialization, rendering loop, and visualization demos (Oscilloscope/Charts).
Definition in file monitor.h.
Macro Definition Documentation
ADD_NEW_TASK_TO_CPU0
#define ADD_NEW_TASK_TO_CPU0 (tagName, taskFunc, taskName, stackSize, params, priority, taskHandle)
Value:
    __sys_log("[%s] [CPU0 +] %s", tagName, taskName);                                               \
    xTaskCreatePinnedToCore(taskFunc, taskName, stackSize, params, priority, taskHandle, 0)
Definition at line 47 of file monitor.h.
                           { vTaskDelay(1); }
#include "ui.h"
void systemInit(){
    __entry("systemInit()");
    lcdInit();
    lcdShowIntroScreen();
    // ADD_NEW_TASK_TO_CPU0("systemInit", lcdTestTask0, "lcdTestTask0", 2048, NULL, 7, NULL);
    ADD_NEW_TASK_TO_CPU1("systemInit", screenControlTask, "screenControlTask", 2048, NULL, 7, NULL);
    __exit("systemInit()");
}
ADD_NEW_TASK_TO_CPU1
#define ADD_NEW_TASK_TO_CPU1 (tagName, taskFunc, taskName, stackSize, params, priority, taskHandle)
Value:
    __sys_log("[%s] [CPU1 +] %s", tagName, taskName);                                               \
    xTaskCreatePinnedToCore(taskFunc, taskName, stackSize, params, priority, taskHandle, 1)
Definition at line 51 of file monitor.h.
IS_SYSTEM_INIT
#define IS_SYSTEM_INIT (systemStage == SYSTEM_INIT)
LOCAL HELPER //////////////////////////////////////////////////////////////////////////////////.
Definition at line 44 of file monitor.h.
IS_SYSTEM_RUNNING
#define IS_SYSTEM_RUNNING (systemStage == SYSTEM_RUNNING)
Definition at line 45 of file monitor.h.
IS_SYSTEM_STOPPED
#define IS_SYSTEM_STOPPED (systemStage == SYSTEM_STOPPED)
Definition at line 46 of file monitor.h.
WAIT_SYSTEM_INIT_COMPLETED
#define WAIT_SYSTEM_INIT_COMPLETED () while (IS_SYSTEM_INIT) { vTaskDelay(1); }
Definition at line 55 of file monitor.h.
                           { vTaskDelay(1); }
Enumeration Type Documentation
ENUM_SYSTEM_MODE
enum ENUM_SYSTEM_MODE
SYSTEM MODE ///////////////////////////////////////////////////////////////////////////////////.
Enumerator
SYSTEM_MODE_DEMO_OSC_CAP
SYSTEM_MODE_DEMO_SPI_CAP
Sample analog signal.
SYSTEM_MODE_DEMO_I2C_CAP
Capture pakages on SPI bus.
SYSTEM_MODE_COUNT
Capture pakages on SPI bus.
Definition at line 25 of file monitor.h.
                      {
    SYSTEM_MODE_DEMO_OSC_CAP        = 0,
    SYSTEM_MODE_DEMO_SPI_CAP        = 1,
    SYSTEM_MODE_DEMO_I2C_CAP        = 2,
    SYSTEM_MODE_COUNT,
};
ENUM_SYSTEM_STAGE
enum ENUM_SYSTEM_STAGE
DEFINITIONS ///////////////////////////////////////////////////////////////////////////////////.
SYSTEM STAGE ////////////////////////////////////////////////////////////////////////////////// Enumeration defining the system operation stages.
Enumerator
SYSTEM_INIT
SYSTEM_RUNNING
System is initializing.
SYSTEM_STOPPED
System is currently running.
SYSTEM_STAGE_COUNT
System has been stopped or halted.
Definition at line 9 of file monitor.h.
                       {
    SYSTEM_INIT    = 0,
    SYSTEM_RUNNING = 1,
    SYSTEM_STOPPED = 2,
    SYSTEM_STAGE_COUNT,
};
Function Documentation
systemInit()
void systemInit ()
TASKS /////////////////////////////////////////////////////////////////////////////////////////.
INIT //////////////////////////////////////////////////////////////////////////////////////////
Definition at line 64 of file monitor.h.
                 {
    __entry("systemInit()");
    lcdInit();
    lcdShowIntroScreen();
    // ADD_NEW_TASK_TO_CPU0("systemInit", lcdTestTask0, "lcdTestTask0", 2048, NULL, 7, NULL);
    ADD_NEW_TASK_TO_CPU1("systemInit", screenControlTask, "screenControlTask", 2048, NULL, 7, NULL);
    __exit("systemInit()");
}
References lcdInit(), lcdShowIntroScreen(), and screenControlTask().
Referenced by app_main().
Variable Documentation
SYSTEM_MODE_STR
const char* SYSTEM_MODE_STR[] static
Initial value:
= {
    "SYSTEM_MODE_DEMO_OSC_CAP",
    "SYSTEM_MODE_DEMO_SPI_CAP",
    "SYSTEM_MODE_DEMO_I2C_CAP",
}
Definition at line 33 of file monitor.h.
{
    "SYSTEM_MODE_DEMO_OSC_CAP",
    "SYSTEM_MODE_DEMO_SPI_CAP",
    "SYSTEM_MODE_DEMO_I2C_CAP",
};
systemMode
volatile flag_t systemMode = SYSTEM_MODE_DEMO_OSC_CAP
Definition at line 39 of file monitor.h.
systemStage
volatile flag_t systemStage = SYSTEM_INIT
Global system stage flag used to represent the overall runtime state. Access to this variable must be protected by systemStageMutex.
Definition at line 18 of file monitor.h.
Referenced by app_main().
systemStageMutex
volatile portMUX_TYPE systemStageMutex = portMUX_INITIALIZER_UNLOCKED
Mutex for synchronizing access to the system stage flag.
Definition at line 21 of file monitor.h.