DO-AN-02: comDriver/oled128x64/oled128x64.c File Reference
oled128x64.c File Reference
#include "../../helper/helper.h"
#include "oled128x64Commands.h"
#include "oled128x64Helpers.h"
#include "oled128x64Log.h"
#include "oled128x64Definitions.h"
#include "oled128x64.h"
Functions
<<<<<<< HEAD=======> > > > > > master def createOLEDDevice (oled128x64Dev_t **oled)
Create and allocate a new OLED device descriptor.
def configOLEDDevice (oled128x64Dev_t *oled, pin_t scl, pin_t sda, flag_t config)
Configure the OLED device I²C pins and communication parameters.
def startupOLEDDevice (oled128x64Dev_t *oled)
Initialize and start up the OLED device (send initialization sequence).
def oledResetView (oled128x64Dev_t *oled)
Reset the OLED control registers to default state (top-left = (0,0)).
def oledTurnOnAllPixels (oled128x64Dev_t *oled)
Turn on all pixels on the OLED display (override RAM content).
def oledShowRAMContent (oled128x64Dev_t *oled)
Display the content stored in OLED RAM (resume from “all pixels on” mode).
def oledFlush (oled128x64Dev_t *oled)
Flush the current framebuffer (canvas) to the OLED display.
def oledOn (oled128x64Dev_t *oled)
def oledOff (oled128x64Dev_t *oled)
def oledFillScreen (oled128x64Dev_t *oled, color_t color)
Fill the entire screen with a uniform color.
def oledSetPixel (oled128x64Dev_t *oled, xy_t row, xy_t col, color_t c)
Set a pixel in the OLED canvas to a given color (1 = ON, 0 = OFF).
def oledDrawEmptyRect (oled128x64Dev_t *oled, xy_t rTopLeft, xy_t cTopLeft, xy_t rBottomRight, xy_t cBottomRight, xy_t edgeSize, color_t color)
Draw an empty (border-only) rectangle on the OLED canvas.
def oledDrawChar (oled128x64Dev_t *oled, xy_t r, xy_t y, char c, color_t cl)
def oledDrawText (oled128x64Dev_t *oled, xy_t r, xy_t c, const char *str, color_t color, bool wrap, byte_t lineHeight)
Draw a text string on the OLED display using the active font.
void drawLineText (oled128x64Dev_t *oled, const char *text, flag_t conf)
Draw text with line param instead of row index of baseline.
Function Documentation
configOLEDDevice()
def configOLEDDevice (oled128x64Dev_t * oled, pin_t scl, pin_t sda, flag_t config)
Configure the OLED device I²C pins and communication parameters.
Parameters
oled Pointer to the OLED device descriptor.
scl GPIO pin number used for the I²C SCL line.
sda GPIO pin number used for the I²C SDA line.
config Configuration flags. See I2C_CONFIG_ORDER enum.
Returns
OKE on success, or error code if configuration fails.
Config SCL, SDA, as MASTER mode + FAST mode speed
Definition at line 50 of file oled128x64.c.
{
    __oledEntry("configOLEDDevice(%p, %d, %d, 0x%02x)", oled, scl, sda, config);
    if(__is_null(oled)) goto configOLED_ReturnERR_NULL;
    if(__is_null(oled->i2cDev)) goto configOLED_ReturnERR_NULL;
    if( configI2CDevice(oled->i2cDev, OLED_ADDR, scl, sda, config) != OKE)
        goto configOLED_ReturnERR;
    __oledExit("configOLEDDevice() : %s", STR(OKE));
    return OKE;
    configOLED_ReturnERR:
        __oledExit("configOLEDDevice() : %s", STR(ERR));
        return ERR;
    configOLED_ReturnERR_NULL:
        __oledExit("configOLEDDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
}
References configI2CDevice(), ERR, ERR_NULL, oled128x64Dev_t::i2cDev, and OKE.
createOLEDDevice()
<<<<<<< HEAD======= > > > > > > master def createOLEDDevice (oled128x64Dev_t ** oled)
Create and allocate a new OLED device descriptor.
Parameters
oled Double pointer to the OLED device handle to be allocated.
Returns
OKE on success, or error code if allocation fails.
Definition at line 18 of file oled128x64.c.
{
    __oledEntry("createOLEDDevice(%p)", oled);
    if(__is_null(oled)) goto ReturnERR_NULL;
    (*oled) = (oled128x64Dev_t*) malloc(sizeof(oled128x64Dev_t));
    if(__is_null(*oled)) goto ReturnERR_NULL;
    (*oled)->height = __oled_h;
    (*oled)->width  = __oled_w;
    (*oled)->canvas = (cell_t*) malloc(sizeof(cell_t) * ((*oled)->width) * ((*oled)->height) / 8);
    if(__is_null((*oled)->canvas)) goto ReturnERR_MALLOC_FAILED;
    if( createI2CDevice(&((*oled)->i2cDev)) != OKE ) goto ReturnERR;
    __oledExit("createOLEDDevice() : %s", STR(OKE));
    return OKE;
    ReturnERR:
        __oledExit("createOLEDDevice() : %s", STR(ERR));
        return ERR;
    ReturnERR_NULL:
        __oledExit("createOLEDDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
    ReturnERR_MALLOC_FAILED:
        __oledExit("createOLEDDevice() : %s", STR(ERR_MALLOC_FAILED));
        return ERR_MALLOC_FAILED;
}
References oled128x64Dev_t::canvas, createI2CDevice(), ERR, ERR_MALLOC_FAILED, ERR_NULL, oled128x64Dev_t::height, oled128x64Dev_t::i2cDev, OKE, and oled128x64Dev_t::width.
drawLineText()
void drawLineText (oled128x64Dev_t * oled, const char * text, flag_t conf)
Draw text with line param instead of row index of baseline.
Parameters
oled Pointer to the OLED device descriptor.
text Text to be draw
conf Config lineH, mode.
Note
conf[7:0]: lineIndex; Range: [0, (screenHeight/lineHeight)].
conf[15:08]: lineHeight; Set 0 for auto determine.
conf[16]: 0 - Call oledResetView(), 1 - Skip oledResetView()
conf[17]: 0 - Call oledFillScreen(), 1 - Skip oledFillScreen()
conf[18]: 0 - Call oledShowRAMContent(), 1 - Skip oledShowRAMContent()
conf[19]: 0 - Call oledFlush(), 1 - Skip oledFlush()
Definition at line 393 of file oled128x64.c.
{
    if(__hasFlagBitClr(conf, 16)) oledResetView(oled);
    if(__hasFlagBitClr(conf, 17)) oledFillScreen(oled, 0);
    if(__hasFlagBitClr(conf, 18)) oledShowRAMContent(oled);
    oledDrawText(oled, ((conf&0xFF)+1)*((conf>>8)&0xFF) + (conf&0xFF)*1, 0, text, 1, 1, ((conf>>8)&0xFF));
    if(__hasFlagBitClr(conf, 19)) oledFlush(oled);
}
References oledDrawText(), oledFillScreen(), oledFlush(), oledResetView(), and oledShowRAMContent().
oledDrawChar()
def oledDrawChar (oled128x64Dev_t * oled, xy_t r, xy_t y, char c, color_t cl)
Definition at line 307 of file oled128x64.c.
{
    // __oledEntry("oled_draw_char(%d, %d, %c, %d)", r, y, c, cl);
    if (c < 0x20 || c > 0x7E) {
        __oledExit("oledDrawChar() : ESP_ERR_INVALID_ARG");
        return ESP_ERR_INVALID_ARG;
    }
    GFXglyph glyph = mainFont.glyph[c - 0x20];
    uint16_t bo = glyph.bitmapOffset;
    xy_t     w  = glyph.width;
    xy_t     h  = glyph.height;
    xy_t     xo = glyph.xOffset;
    xy_t     yo = glyph.yOffset;
    xy_t bitmap_top_x = r + yo;
    xy_t bitmap_left_y = y + xo;
    byte_t bits = 0;
    byte_t bitCount = 0;
    REPT(xy_t, yy, 0, h) {
        REPT(xy_t, xx, 0, w) {
            if (bitCount == 0) {
                bits = mainFont.bitmap[bo++];
                bitCount = 8;
            }
            if (bits & 0x80) {
                xy_t pixel_x = bitmap_top_x + yy;
                xy_t pixel_y = bitmap_left_y + xx;
                if (pixel_x >= __min_x && pixel_x < (oled->height) &&
                    pixel_y >= __min_y && pixel_y < (oled->width)) {
                    oledSetPixel(oled, pixel_x, pixel_y, cl);
                }
            }
            bits <<= 1;
            bitCount--;
        }
    }
    // __oledExit("oledDrawChar() : OKE");
    return OKE;
}
References bitmap, bitmapOffset, GFXglyph, glyph, oled128x64Dev_t::height, height, mainFont, OKE, oledSetPixel(), oled128x64Dev_t::width, width, xOffset, and yOffset.
Referenced by oledDrawText().
oledDrawEmptyRect()
def oledDrawEmptyRect (oled128x64Dev_t * oled, xy_t rTopLeft, xy_t cTopLeft, xy_t rBottomRight, xy_t cBottomRight, xy_t edgeSize, color_t color)
Draw an empty (border-only) rectangle on the OLED canvas.
Parameters
oled Pointer to the OLED device descriptor.
rTopLeft Top-left corner row index.
cTopLeft Top-left corner column index.
rBottomRight Bottom-right corner row index.
cBottomRight Bottom-right corner column index.
edgeSize Thickness of rectangle border (in pixels).
color Color value (1 = ON, 0 = OFF).
Returns
OKE on success, ERR_INVALID_ARG if coordinates are invalid.
Definition at line 270 of file oled128x64.c.
{
    if (edgeSize < 1) return OKE;
    if (rTopLeft < 0 || rTopLeft >= oled->height ||
        cTopLeft < 0 || cTopLeft >= oled->width ||
        rBottomRight < 0 || rBottomRight >= oled->height ||
        cBottomRight < 0 || cBottomRight >= oled->width)
        return ERR_INVALID_ARG;
    if (rTopLeft > rBottomRight || cTopLeft > cBottomRight)
        return ERR_INVALID_ARG;
    if (rBottomRight - rTopLeft <= 1 || cBottomRight - cTopLeft <= 1)
        return OKE;
    // Draw vertical edges
    REP(x, rTopLeft, rBottomRight + 1) {
        oledSetPixel(oled, x, cTopLeft, color);
        oledSetPixel(oled, x, cBottomRight, color);
    }
    // Draw horizontal edges
    REP(y, cTopLeft, cBottomRight + 1) {
        oledSetPixel(oled, rTopLeft, y, color);
        oledSetPixel(oled, rBottomRight, y, color);
    }
    // Recursive shrink
    return oledDrawEmptyRect(oled,
                             rTopLeft + 1, cTopLeft + 1,
                             rBottomRight - 1, cBottomRight - 1,
                             edgeSize - 1, color);
}
References ERR_INVALID_ARG, oled128x64Dev_t::height, OKE, oledDrawEmptyRect(), oledSetPixel(), and oled128x64Dev_t::width.
Referenced by oledDrawEmptyRect().
oledDrawText()
def oledDrawText (oled128x64Dev_t * oled, xy_t r, xy_t c, const char * str, color_t cl, bool wrap, byte_t lineHeight)
Draw a text string on the OLED display using the active font.
Parameters
oled Pointer to the OLED device descriptor.
r Starting row (baseline position).
c Starting column position.
str Pointer to the null-terminated text string to render.
cl Text color (1 = ON, 0 = OFF).
wrap Enable word wrapping (true = wrap at screen edge).
lineHeight Line spacing (in pixels); 0 to use font default.
Returns
OKE on success, ERR_INVALID_ARG if string is NULL or invalid.
Definition at line 351 of file oled128x64.c.
{
    __oledEntry("oledDrawText(%d, %d, \"%s\", %d, wrap=%d, lh=%d)",
                r, c, str, color, wrap, lineHeight);
    if (!oled || !str)
        return ERR_INVALID_ARG;
    xy_t cursor_r = r;
    xy_t cursor_c = c;
    byte_t finalLineHeight = __max(lineHeight, defaultTextH(mainFont));
    while (*str) {
        char ch = *str++;
        if (ch == '\n') {
            cursor_c = 0;
            cursor_r += finalLineHeight;
            continue;
        }
        if (ch < 0x20 || ch > 0x7E)
            continue;
        GFXglyph glyph = mainFont.glyph[ch - 0x20];
        // Wrap if needed
        if (wrap && (cursor_c + glyph.xAdvance > oled->width)) {
            cursor_c = 0;
            cursor_r += finalLineHeight;
        }
        oledDrawChar(oled, cursor_r, cursor_c, ch, color);
        cursor_c += glyph.xAdvance;
    }
    __oledExit("oledDrawText() : OKE");
    return OKE;
}
References ERR_INVALID_ARG, GFXglyph, glyph, mainFont, OKE, oledDrawChar(), oled128x64Dev_t::width, and xAdvance.
Referenced by drawLineText().
oledFillScreen()
def oledFillScreen (oled128x64Dev_t * oled, color_t color)
Fill the entire screen with a uniform color.
Parameters
oled Pointer to the OLED device descriptor.
color Pixel value (1 = ON, 0 = OFF).
Returns
OKE on success.
Definition at line 240 of file oled128x64.c.
{
    REP(i, 0, (oled->height) * (oled->width) / 8){
        (oled->canvas)[i] = ((color)?(0xFF):(0x0));
    }
    return OKE;
}
References oled128x64Dev_t::canvas, oled128x64Dev_t::height, OKE, and oled128x64Dev_t::width.
Referenced by drawLineText().
oledFlush()
def oledFlush (oled128x64Dev_t * oled)
Flush the current framebuffer (canvas) to the OLED display.
Parameters
oled Pointer to the OLED device descriptor.
Returns
OKE on success.
Definition at line 189 of file oled128x64.c.
{
    __oledEntry("oledFlush(%p)", oled);
    uint8_t cmds[] = {
        SSD1306_DEACTIVATE_SCROLL,
        SSD1306_SET_MEMORY_MODE, 0x00,
        SSD1306_SET_COLUMN_ADDR, 0x00, 0x7F,
        SSD1306_SET_PAGE_ADDR, 0x00, 0x07,
        SSD1306_SET_START_LINE(0),
        SSD1306_SET_SEG_REMAP_0,
        SSD1306_SET_COM_SCAN_INC,
        SSD1306_SET_DISPLAY_OFFSET, 0x00,
        // SSD1306_INVERT_DISPLAY,
        // SSD1306_ENTIRE_DISPLAY_RESUME,
        // SSD1306_DISPLAY_ON
    };
    def ret;
    ret = i2cSetTransmitBuffer(oled->i2cDev, cmds, sizeof(cmds));
    if(ret != OKE) goto oledFlush_ReturnERR;
    ret = i2cSendBuffer(oled->i2cDev, OLED_ADDR, 0, __mask32(I2C_RESET_TX_INDEX));
    if(ret != OKE) goto oledFlush_ReturnERR;
    ret = i2cSetTransmitBuffer(oled->i2cDev, oled->canvas, ((oled->height) * (oled->width) / 8));
    if(ret != OKE) goto oledFlush_ReturnERR;
    ret = i2cSendByte(oled->i2cDev, OLED_ADDR, 0, SSD1306_DATA, __mask32(I2C_DIS_STOP_CONDI));
    if(ret != OKE) goto oledFlush_ReturnERR;
    ret = i2cSendBuffer(oled->i2cDev, OLED_ADDR, 0, __mask32(I2C_SKIP_ADDR_FRAME) |  __mask32(I2C_DIS_START_CONDI) | __mask32(I2C_RESET_TX_INDEX));
    if(ret != OKE) goto oledFlush_ReturnERR;
    __oledExit("oledFlush() : %s", STR(OKE));
    return OKE;
    oledFlush_ReturnERR:
        __oledExit("oledFlush() : %s", STR(ERR));
        return ERR;
}
References oled128x64Dev_t::canvas, ERR, oled128x64Dev_t::height, I2C_DIS_START_CONDI, I2C_DIS_STOP_CONDI, I2C_RESET_TX_INDEX, I2C_SKIP_ADDR_FRAME, oled128x64Dev_t::i2cDev, i2cSendBuffer(), i2cSendByte(), i2cSetTransmitBuffer(), OKE, and oled128x64Dev_t::width.
Referenced by drawLineText().
oledOff()
def oledOff (oled128x64Dev_t * oled)
Definition at line 235 of file oled128x64.c.
{
    i2cSendDoubleByte(oled->i2cDev, OLED_ADDR, 0, SSD1306_COMMAND, SSD1306_DISPLAY_OFF, 0);
    return OKE;
}
References oled128x64Dev_t::i2cDev, i2cSendDoubleByte(), and OKE.
oledOn()
def oledOn (oled128x64Dev_t * oled)
Definition at line 230 of file oled128x64.c.
{
    i2cSendDoubleByte(oled->i2cDev, OLED_ADDR, 0, SSD1306_COMMAND, SSD1306_DISPLAY_ON, 0);
    return OKE;
}
References oled128x64Dev_t::i2cDev, i2cSendDoubleByte(), and OKE.
oledResetView()
def oledResetView (oled128x64Dev_t * oled)
Reset the OLED control registers to default state (top-left = (0,0)).
Parameters
oled Pointer to the OLED device descriptor.
Returns
OKE on success.
Definition at line 117 of file oled128x64.c.
{
    __oledEntry("oledResetView(%p)", oled);
    const uint8_t cmds[] = {
        SSD1306_COMMAND,
        // SSD1306_DISPLAY_OFF,
        SSD1306_DEACTIVATE_SCROLL,
        SSD1306_SET_MEMORY_MODE, 0x00,
        SSD1306_SET_COLUMN_ADDR, 0x00, 0x7F,
        SSD1306_SET_PAGE_ADDR, 0x00, 0x07,
        SSD1306_SET_START_LINE(0),
        SSD1306_SET_SEG_REMAP_0,
        SSD1306_SET_COM_SCAN_INC,
        SSD1306_SET_DISPLAY_OFFSET, 0x00,
        // SSD1306_NORMAL_DISPLAY,
        SSD1306_ENTIRE_DISPLAY_RESUME,
        SSD1306_DISPLAY_ON
    };
    def ret;
    ret = i2cSetTransmitBuffer(oled->i2cDev, cmds, sizeof(cmds));
    if(ret != OKE) goto oledFlush_ReturnERR;
    ret = i2cSendBuffer(oled->i2cDev, OLED_ADDR, 0, __mask32(I2C_RESET_TX_INDEX));
    if(ret != OKE) goto oledFlush_ReturnERR;
    __oledExit("oledResetView() : %s", STR(OKE));
    return OKE;
    oledFlush_ReturnERR:
        __oledExit("oledResetView() : %s", STR(ERR));
        return ERR;
}
References ERR, I2C_RESET_TX_INDEX, oled128x64Dev_t::i2cDev, i2cSendBuffer(), and OKE.
Referenced by drawLineText().
oledSetPixel()
def oledSetPixel (oled128x64Dev_t * oled, xy_t row, xy_t col, color_t c)
Set a pixel in the OLED canvas to a given color (1 = ON, 0 = OFF).
Parameters
oled Pointer to the OLED device descriptor.
row Pixel row index (0–height-1).
col Pixel column index (0–width-1).
c Color value (1 = ON, 0 = OFF).
Returns
OKE on success, ERR_INVALID_ARG if coordinates are out of bounds.
Page index (0–7)
Bit position in the byte (0–7)
Definition at line 247 of file oled128x64.c.
{
    __oledLog1("** oledSetPixel(%p, %d, %d)", oled, row, col);
    // Validate coordinates
    if (row < 0 || row >= oled->height || col < 0 || col >= oled->width)
        return ERR_INVALID_ARG;
    // Each page = 8 rows (0–7)
    xy_t pageIndex = row >> 3;
    xy_t bitIndex  = row & 0x7;
    // Compute byte index in framebuffer
    xy_t canvasIndex = pageIndex * oled->width + col;
    // Write bit in framebuffer
    if (c)
        oled->canvas[canvasIndex] |= __mask8(bitIndex);
    else
        oled->canvas[canvasIndex] &= __inv_mask8(bitIndex);
    return OKE;
}
References oled128x64Dev_t::canvas, ERR_INVALID_ARG, oled128x64Dev_t::height, OKE, and oled128x64Dev_t::width.
Referenced by oledDrawChar(), and oledDrawEmptyRect().
oledShowRAMContent()
def oledShowRAMContent (oled128x64Dev_t * oled)
Display the content stored in OLED RAM (resume from “all pixels on” mode).
Parameters
oled Pointer to the OLED device descriptor.
Returns
OKE on success.
Definition at line 166 of file oled128x64.c.
{
    __oledEntry("oledShowRAMContent(%p)", oled);
    if(__is_null(oled)) {
        __oledExit("oledTurnOnAllPixels() : %s", STR(ERR_NULL));
        return ERR_NULL;
    }
    def ret;
    ret = i2cSendDoubleByte(oled->i2cDev, OLED_ADDR, 0, SSD1306_COMMAND, SSD1306_DISPLAY_ON, 0);
    if(ret != OKE) goto oledShowRAMContent_ReturnERR;
    ret = i2cSendDoubleByte(oled->i2cDev, OLED_ADDR, 0, SSD1306_COMMAND, SSD1306_ENTIRE_DISPLAY_RESUME, 0);
    if(ret != OKE) goto oledShowRAMContent_ReturnERR;
    __oledExit("oledTurnOnAllPixels() : %s", STR(OKE));
    return OKE;
    oledShowRAMContent_ReturnERR:
        __oledExit("oledShowRAMContent() : %s", STR(ERR));
        return ERR;
}
References ERR, ERR_NULL, oled128x64Dev_t::i2cDev, i2cSendDoubleByte(), and OKE.
Referenced by drawLineText().
oledTurnOnAllPixels()
def oledTurnOnAllPixels (oled128x64Dev_t * oled)
Turn on all pixels on the OLED display (override RAM content).
Parameters
oled Pointer to the OLED device descriptor.
Returns
OKE on success.
Definition at line 153 of file oled128x64.c.
{
    __oledEntry("oledTurnOnAllPixels(%p)", oled);
    if(__is_null(oled)) {
        __exit("oledTurnOnAllPixels() : %s", STR(ERR_NULL));
        return ERR_NULL;
    }
    i2cSendDoubleByte(oled->i2cDev, OLED_ADDR, 0, SSD1306_COMMAND, SSD1306_DISPLAY_ON, 0);
    __oledExit("oledTurnOnAllPixels() : %s", STR(OKE));
    return OKE;
}
References ERR_NULL, oled128x64Dev_t::i2cDev, i2cSendDoubleByte(), and OKE.
startupOLEDDevice()
def startupOLEDDevice (oled128x64Dev_t * oled)
Initialize and start up the OLED device (send initialization sequence).
Parameters
oled Pointer to the OLED device descriptor.
Returns
OKE on success, or error code if initialization fails.
Definition at line 72 of file oled128x64.c.
{
    __oledEntry("startupOLEDDevice(%p)", oled);
    if(__is_null(oled)) goto startupOLED_ReturnERR_NULL;
    if(startupI2CDevice(oled->i2cDev) != OKE) goto startupOLED_ReturnERR;
    byte_t init_commands[] = {
        SSD1306_COMMAND,
        SSD1306_DISPLAY_OFF,
        SSD1306_SET_DISPLAY_CLOCK_DIV,      0x80,
        SSD1306_SET_MULTIPLEX_RATIO,        0x3F,
        SSD1306_SET_DISPLAY_OFFSET,         0x00,
        SSD1306_SET_START_LINE(0),
        SSD1306_CHARGE_PUMP,                0x14,
        SSD1306_SET_MEMORY_MODE,            0x00,
        SSD1306_SET_COM_PINS,               0x12,
        SSD1306_SET_CONTRAST,               0xCF,
        SSD1306_SET_PRECHARGE,              0xF1,
        SSD1306_SET_VCOM_DETECT,            0x40,
        // SSD1306_INVERT_DISPLAY,
        SSD1306_NORMAL_DISPLAY,
        SSD1306_DISPLAY_ON,
        SSD1306_ENTIRE_DISPLAY_ON
    };
    i2cSetTransmitBuffer(oled->i2cDev, init_commands, sizeof(init_commands));
    __oledLog("Send start-up sequence ...");
    if( i2cSendBuffer(oled->i2cDev, OLED_ADDR, I2C_WRITE_MODE,
                __flagMask(I2C_RESET_RX_INDEX) | __flagMask(I2C_RESET_TX_INDEX)) != OKE)
        goto startupOLED_ReturnERR;
    __oledExit("startupOLEDDevice() : %s", STR(OKE));
        return OKE;
    startupOLED_ReturnERR:
        __oledExit("startupOLEDDevice() : %s", STR(ERR));
        return ERR;
    startupOLED_ReturnERR_NULL:
        __oledExit("startupOLEDDevice() : %s", STR(ERR_NULL));
        return ERR_NULL;
}
References ERR, ERR_NULL, I2C_RESET_RX_INDEX, I2C_RESET_TX_INDEX, I2C_WRITE_MODE, oled128x64Dev_t::i2cDev, i2cSendBuffer(), i2cSetTransmitBuffer(), OKE, and startupI2CDevice().