DO-AN-02: AppComponents/P16Com/P16Com.c File Reference
P16Com.c File Reference
16-bit Parallel Communication Driver Implementation
#include "P16Com.h"
Functions
P16Dev_t * P16ComNew ()
Allocates a new P16Dev_t object.
void P16Delete (P16Dev_t *Dev)
Deallocate memory for P16Dev_t object.
DefaultRet_t P16ComConfigCtl (P16Dev_t *Dev, const Pin_t *CtlPins)
Configure Control pins mapping and calculate IO Masks.
DefaultRet_t P16ComConfigDat (P16Dev_t *Dev, const Pin_t *DatPins)
Configure Data pins mapping and calculate IO Masks.
DefaultRet_t P16ComInit (P16Dev_t *Dev)
Initialize the driver GPIOs and Flags.
DefaultRet_t P16ComReConfig (P16Dev_t *Dev)
Re-initializes the driver based on existing configuration.
void P16ComMakeReset (P16Dev_t *Dev)
Generate a hard reset pulse.
void P16ComWrite (P16Dev_t *Dev, P16Data_t Data)
Write a single word to the bus.
void P16ComWriteArray (P16Dev_t *Dev, P16Data_t *DataArr, P16Size_t Size)
Write a block of data to the bus (Burst Write)
P16Data_t P16ComRead (P16Dev_t *Dev)
Read a single word from the bus.
void P16ComReadArray (P16Dev_t *Dev, P16Data_t *pBuff, P16Size_t Size)
Read a block of data from the bus (Burst Read)
Detailed Description
16-bit Parallel Communication Driver Implementation
Author
Nguyen Thanh Phu
Definition in file P16Com.c.
Function Documentation
P16ComConfigCtl()
DefaultRet_t P16ComConfigCtl (P16Dev_t * Dev, const Pin_t * CtlPins)
Configure Control pins mapping and calculate IO Masks.
Parameters
Dev Pointer to the P16Dev_t object
CtlPins Array of 5 Control Pins (RD, WR, CS, RS, RST)
Returns
STAT_OKE on success, STAT_ERR on invalid pin
Configure and Mask Control Pins
Definition at line 42 of file P16Com.c.
{
    P16Entry("P16ComConfigCtl(%p, %p)", Dev, CtlPins);
    if(IsNull(Dev) || IsNull(CtlPins)){
        P16ReturnWithLog(STAT_ERR_NULL, "P16ComConfigCtl() : STAT_ERR_NULL");
    }
    Dev->CtlIOMask = 0;
    REPN(i, P16COM_CTL_PIN_NUM){
        if(IsStandardPin(CtlPins[i])){
            Dev->CtlPinArr[i] = CtlPins[i];
            Dev->CtlIOMask |= Mask64(CtlPins[i]);
        } else {
            P16Err("[P16ComConfigCtl] Invalid Control Pin at index %d", i);
            P16ReturnWithLog(STAT_ERR_INVALID_ARG, "P16ComConfigCtl() : STAT_ERR_INVALID_ARG");
        }
    }
    P16ReturnWithLog(STAT_OKE, "P16ComConfigCtl() : STAT_OKE");
}
References P16Dev_t::CtlIOMask, P16Dev_t::CtlPinArr, IsNull, IsStandardPin, Mask64, P16COM_CTL_PIN_NUM, P16Entry, P16Err, P16ReturnWithLog, REPN, STAT_ERR_INVALID_ARG, STAT_ERR_NULL, and STAT_OKE.
Referenced by LCD32Config().
P16ComConfigDat()
DefaultRet_t P16ComConfigDat (P16Dev_t * Dev, const Pin_t * DatPins)
Configure Data pins mapping and calculate IO Masks.
Parameters
Dev Pointer to the P16Dev_t object
DatPins Array of 16 Data Pins (D0..D15)
Returns
STAT_OKE on success, STAT_ERR on invalid pin
Configure and Mask Data Pins
Definition at line 65 of file P16Com.c.
{
    P16Entry("P16ComConfigDat(%p, %p)", Dev, DatPins);
    if(IsNull(Dev) || IsNull(DatPins)){
        P16ReturnWithLog(STAT_ERR_NULL, "P16ComConfigDat() : STAT_ERR_NULL");
    }
    Dev->DatIOMask = 0;
    REPN(i, P16COM_DAT_PIN_NUM){
        if(IsStandardPin(DatPins[i])){
            Dev->DatPinArr[i] = DatPins[i];
            Dev->DatIOMask |= Mask64(DatPins[i]);
        } else {
            P16Err("[P16ComConfigDat] Invalid Data Pin at index %d", i);
            P16ReturnWithLog(STAT_ERR_INVALID_ARG, "P16ComConfigDat() : STAT_ERR_INVALID_ARG");
        }
    }
    P16ReturnWithLog(STAT_OKE, "P16ComConfigDat() : STAT_OKE");
}
References P16Dev_t::DatIOMask, P16Dev_t::DatPinArr, IsNull, IsStandardPin, Mask64, P16COM_DAT_PIN_NUM, P16Entry, P16Err, P16ReturnWithLog, REPN, STAT_ERR_INVALID_ARG, STAT_ERR_NULL, and STAT_OKE.
Referenced by LCD32Config().
P16ComInit()
DefaultRet_t P16ComInit (P16Dev_t * Dev)
Initialize the driver GPIOs and Flags.
Initializes the GPIOs for the parallel interface.
Configure DATA pins
Note
Use pre-calculated DatIOMask for speed and sync
Normal state is INPUT (Safe Mode / High-Z)
Configure CONTROL pins
Set Control pins to OUTPUT (Push-Pull)
Set Control pins to IDLE state (High for active-low signals)
Mark as initialized
Definition at line 88 of file P16Com.c.
{
    P16Entry("P16ComInit(%p)", Dev);
    if(IsNull(Dev)) {
        P16ReturnWithLog(STAT_ERR_NULL, "P16ComInit() : STAT_ERR_NULL");
    }
    if(Dev->DatIOMask == 0){
        P16Err("[P16ComInit] DatIOMask is empty! Run Config first?");
        P16ReturnWithLog(STAT_ERR_INIT_FAILED, "P16ComInit() : STAT_ERR_INIT_FAILED");
    }
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 1)
        IOConfigAsOutput(Dev->DatIOMask, -1, -1);
    #else
        IOConfigAsInput(Dev->DatIOMask, -1, -1);
    #endif
    if(Dev->CtlIOMask == 0){
        P16Err("[P16ComInit] CtlIOMask is empty! Run Config first?");
        P16ReturnWithLog(STAT_ERR_INIT_FAILED, "P16ComInit() : STAT_ERR_INIT_FAILED");
    }
    IOConfigAsOutput(Dev->CtlIOMask, -1, -1);
    IOStandardSet(Dev->CtlIOMask);
    Dev->StatusFlag |= P16COM_INITIALIZED;
    P16ReturnWithLog(STAT_OKE, "P16ComInit() : STAT_OKE");
}
References P16Dev_t::CtlIOMask, P16Dev_t::DatIOMask, IOConfigAsInput(), IOConfigAsOutput(), IOStandardSet, IsNull, P16COM_INITIALIZED, P16Entry, P16Err, P16ReturnWithLog, STAT_ERR_INIT_FAILED, STAT_ERR_NULL, STAT_OKE, and P16Dev_t::StatusFlag.
Referenced by LCD32Init(), and P16ComReConfig().
P16ComMakeReset()
void P16ComMakeReset (P16Dev_t * Dev)
Generate a hard reset pulse.
Performs a hardware reset sequence using the Reset pin.
Pulse Reset: Low -> Delay -> High
Definition at line 135 of file P16Com.c.
{
    #if (P16COM_INIT_CHECK_EN == 1)
        if( !((Dev->StatusFlag) & P16COM_INITIALIZED) ){
            P16Err("[P16ComMakeReset] Device not initialized!");
            return;
        }
    #endif
    P16SetLowResetPin(Dev);
    P16BlockingDelay(P16HalfClockCycle);
    P16SetHighResetPin(Dev);
    P16BlockingDelay(P16HalfClockCycle);
}
References P16BlockingDelay, P16COM_INITIALIZED, P16Err, P16HalfClockCycle, P16SetHighResetPin, P16SetLowResetPin, and P16Dev_t::StatusFlag.
P16ComNew()
P16Dev_t * P16ComNew ()
Allocates a new P16Dev_t object.
Allocates memory for a new P16Dev_t object.
Allocate memory
Preset Ctl/Dat pin arrays to -1 (Invalid/Unused)
Preset status to uninitialized
Definition at line 10 of file P16Com.c.
                      {
    P16Dev_t * devPtr = (P16Dev_t *) malloc(sizeof(P16Dev_t));
    if (devPtr == NULL) {
        P16Err("[P16ComNew] Malloc failed!");
        return NULL;
    }
    REPN(i, P16COM_DAT_PIN_NUM_W_PADDING){
        devPtr->DatPinArr[i] = -1;
    }
    REPN(i, P16COM_CTL_PIN_NUM_W_PADDING){
        devPtr->CtlPinArr[i] = -1;
    }
    devPtr->StatusFlag = 0;
    devPtr->CtlIOMask = 0;
    devPtr->DatIOMask = 0;
    return devPtr;
}
References P16Dev_t::CtlIOMask, P16Dev_t::CtlPinArr, P16Dev_t::DatIOMask, P16Dev_t::DatPinArr, P16COM_CTL_PIN_NUM_W_PADDING, P16COM_DAT_PIN_NUM_W_PADDING, P16Err, REPN, and P16Dev_t::StatusFlag.
P16ComRead()
P16Data_t P16ComRead (P16Dev_t * Dev)
Read a single word from the bus.
Reads a single 16-bit value from the bus.
Activate Read Strobe
Sample Data
Deactivate Read Strobe
Definition at line 236 of file P16Com.c.
{
    #if (P16COM_INIT_CHECK_EN == 1)
        if( !((Dev->StatusFlag) & P16COM_INITIALIZED) ){
            P16Err("[P16ComRead] Device not initialized!");
            return 0;
        }
    #endif
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 1)
        IOConfigAsInput(Dev->DatIOMask, -1, -1);
    #endif
    P16SetLowReadPin(Dev);
    P16BlockingDelay(P16HalfClockCycle);
    uint64_t portState = IOStandardGet();
    uint16_t result = 0;
    REPN(i, 16){
        if ( (portState >> Dev->DatPinArr[i]) & 0x1 ) {
            result |= (1 << i);
        }
    }
    P16SetHighReadPin(Dev);
    P16BlockingDelay(P16HalfClockCycle);
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 1)
        IOConfigAsOutput(Dev->DatIOMask, -1, -1);
    #endif
    return result;
}
References P16Dev_t::DatIOMask, P16Dev_t::DatPinArr, IOConfigAsInput(), IOConfigAsOutput(), IOStandardGet, P16BlockingDelay, P16COM_INITIALIZED, P16Err, P16HalfClockCycle, P16SetHighReadPin, P16SetLowReadPin, REPN, and P16Dev_t::StatusFlag.
Referenced by LCD32Init().
P16ComReadArray()
void P16ComReadArray (P16Dev_t * Dev, P16Data_t * pBuff, P16Size_t Size)
Read a block of data from the bus (Burst Read)
Reads an array of 16-bit values from the bus (Burst Read)
Definition at line 276 of file P16Com.c.
{
    P16Entry("P16ComReadArray(%p, %p, %d)", Dev, pBuff, Size);
    #if (P16COM_INIT_CHECK_EN == 1)
        if( !((Dev->StatusFlag) & P16COM_INITIALIZED) ){
            P16Err("[P16ComReadArray] Device not initialized!");
            return;
        }
    #endif
    if(IsNull(pBuff) || IsNotPos(Size)){
        P16Err("[P16ComReadArray] Buffer is NULL or Size not valid!");
        return;
    }
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 1)
        IOConfigAsInput(Dev->DatIOMask, -1, -1);
    #endif
    REPN(j, Size){
        P16SetLowReadPin(Dev);
        P16BlockingDelay(P16HalfClockCycle);
        uint64_t portState = IOStandardGet();
        uint16_t val = 0;
        REPN(i, 16){
            if ( (portState >> Dev->DatPinArr[i]) & 0x1 ) {
                val |= (1 << i);
            }
        }
        pBuff[j] = val;
        P16SetHighReadPin(Dev);
        P16BlockingDelay(P16HalfClockCycle);
    }
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 1)
        IOConfigAsOutput(Dev->DatIOMask, -1, -1);
    #endif
    P16Exit("P16ComReadArray() : Done");
}
References P16Dev_t::DatIOMask, P16Dev_t::DatPinArr, IOConfigAsInput(), IOConfigAsOutput(), IOStandardGet, IsNotPos, IsNull, P16BlockingDelay, P16COM_INITIALIZED, P16Entry, P16Err, P16Exit, P16HalfClockCycle, P16SetHighReadPin, P16SetLowReadPin, REPN, and P16Dev_t::StatusFlag.
P16ComReConfig()
DefaultRet_t P16ComReConfig (P16Dev_t * Dev)
Re-initializes the driver based on existing configuration.
Parameters
Dev Pointer to the P16Dev_t object
Returns
STAT_OKE on success
Definition at line 129 of file P16Com.c.
{
    P16Entry("P16ComReConfig(%p)", Dev);
    return P16ComInit(Dev);
}
References P16ComInit(), and P16Entry.
P16ComWrite()
void P16ComWrite (P16Dev_t * Dev, P16Data_t Data)
Write a single word to the bus.
Writes a single 16-bit value to the bus.
Switch to OUTPUT using pre-calculated mask
Calculate Bit Masks
Drive Data to Pins
Strobe Write
Switch back to INPUT (Safe Mode)
Definition at line 151 of file P16Com.c.
{
    #if (P16COM_INIT_CHECK_EN == 1)
        if( !((Dev->StatusFlag) & P16COM_INITIALIZED) ){
            P16Err("[P16ComWrite] Device not initialized!");
            return;
        }
    #endif
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 0)
        IOConfigAsOutput(Dev->DatIOMask, -1, -1);
    #endif
    uint64_t MaskSet = 0, MaskClr = 0;
    REPN(i, 16){
        (Data & (1 << i)) ?
        (MaskSet |= (1ULL << Dev->DatPinArr[i])) :
        (MaskClr |= (1ULL << Dev->DatPinArr[i])) ;
    }
    IOStandardSet(MaskSet);
    IOStandardClr(MaskClr);
    P16MakeWritePulse(Dev);
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 0)
        IOConfigAsInput(Dev->DatIOMask, -1, -1);
    #endif
}
References P16Dev_t::DatIOMask, P16Dev_t::DatPinArr, IOConfigAsInput(), IOConfigAsOutput(), IOStandardClr, IOStandardSet, P16COM_INITIALIZED, P16Err, P16MakeWritePulse, REPN, and P16Dev_t::StatusFlag.
Referenced by LCD32DirectlyWritePixel(), LCD32WriteCmd(), and LCD32WriteData().
P16ComWriteArray()
void P16ComWriteArray (P16Dev_t * Dev, P16Data_t * DataArr, P16Size_t Size)
Write a block of data to the bus (Burst Write)
Writes an array of 16-bit values to the bus (Burst Write)
Switch to OUTPUT ONCE for the whole burst
Map bits
Drive Data
Strobe Write
Switch back to INPUT
Definition at line 187 of file P16Com.c.
{
    P16Entry("P16ComWriteArray(%p, %p, %d)", Dev, DataArr, Size);
    #if (P16COM_INIT_CHECK_EN == 1)
        if( !((Dev->StatusFlag) & P16COM_INITIALIZED) ){
            P16Err("[P16ComWriteArray] Device not initialized!");
            return;
        }
    #endif
    if(IsNull(DataArr) || IsNotPos(Size)){
        P16Err("[P16ComWriteArray] DataArr is NULL or Size not valid!");
        return;
    }
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 0)
        IOConfigAsOutput(Dev->DatIOMask, -1, -1);
    #endif
    REPN(j, Size){
        P16Data_t currentData = DataArr[j];
        uint64_t MaskSet = 0, MaskClr = 0;
        REPN(i, 16){
            (currentData & (1 << i)) ?
            (MaskSet |= (1ULL << Dev->DatPinArr[i])) :
            (MaskClr |= (1ULL << Dev->DatPinArr[i])) ;
        }
        IOStandardSet(MaskSet);
        IOStandardClr(MaskClr);
        P16MakeWritePulse(Dev);
    }
    #if (P16COM_DB_NORMAL_OUTPUT_EN == 0)
        IOConfigAsInput(Dev->DatIOMask, -1, -1);
    #endif
    P16Exit("P16ComWriteArray() : Done");
}
References P16Dev_t::DatIOMask, P16Dev_t::DatPinArr, IOConfigAsInput(), IOConfigAsOutput(), IOStandardClr, IOStandardSet, IsNotPos, IsNull, P16COM_INITIALIZED, P16Entry, P16Err, P16Exit, P16MakeWritePulse, REPN, and P16Dev_t::StatusFlag.
Referenced by LCD32FlushCanvas().
P16Delete()
void P16Delete (P16Dev_t * Dev)
Deallocate memory for P16Dev_t object.
Parameters
Dev Pointer to the P16Dev_t object
Definition at line 35 of file P16Com.c.
{
    if(Dev != NULL){
        free(Dev);
    }
}