DO-AN-02: main/ui.h File Reference
ui.h File Reference
#include "../helper/general.h"
#include "../comDriver/lcd32/lcd32.h"
#include "../cds/circularBuffer/cbuff.h"
Classes
struct gridInfo_t
Structure defining grid layout properties for graphs.
Macros
#define COLOR_ERROR 0xc8a6
Color definitions (RGB565 format).
#define COLOR_GIRD 0xef9d
Color for grid lines.
#define COLOR_AXIS 0x2104
Color for axis lines.
#define COLOR_AXIS_TEXT 0xFF
Color for axis text labels.
#define COLOR_LEGEND_BG 0xef7d
Background color for legends.
#define COLOR_CHART_01 0xd6a0
Color for chart series 1.
#define COLOR_CHART_02 0xf96e
Color for chart series 2.
#define COLOR_CHART_03 0x356c
Color for chart series 3.
#define COLOR_CHART_04 0x449e
Color for chart series 4.
Typedefs
typedef struct gridInfo_t gridInfo_t
Structure defining grid layout properties for graphs.
Enumerations
enum SCREEN_FLAG_BIT_ORDER { SCREEN_RENDER = 0 , SCREEN_TURN_ON = 0 , SCREEN_TURN_OFF = 0 , SCREEN_FLAG_BIT_ORDER_NUMBER }
Bit definitions for screen control flags.
Functions
void lcdInit ()
Initialize the LCD device and configure pins.
void lcdShowIntroScreen ()
Display the project introduction screen.
void screenControlTask (void *pv)
Task to handle screen updates, rendering, and power states based on event flags.
Variables
static const gridInfo_t gridInfoTable []
Lookup table for different grid density configurations.
lcd32Dev_t * lcd
Pointer to the global LCD device instance.
volatile flag_t screenFlag = SYSTEM_INIT
Global flag for screen state management.
portMUX_TYPE screenFlagMutex = portMUX_INITIALIZER_UNLOCKED
Mutex for protecting screenFlag access.
Macro Definition Documentation
COLOR_AXIS
#define COLOR_AXIS 0x2104
Color for axis lines.
Definition at line 34 of file ui.h.
COLOR_AXIS_TEXT
#define COLOR_AXIS_TEXT 0xFF
Color for axis text labels.
Definition at line 35 of file ui.h.
COLOR_CHART_01
#define COLOR_CHART_01 0xd6a0
Color for chart series 1.
Definition at line 37 of file ui.h.
COLOR_CHART_02
#define COLOR_CHART_02 0xf96e
Color for chart series 2.
Definition at line 38 of file ui.h.
COLOR_CHART_03
#define COLOR_CHART_03 0x356c
Color for chart series 3.
Definition at line 39 of file ui.h.
COLOR_CHART_04
#define COLOR_CHART_04 0x449e
Color for chart series 4.
Definition at line 40 of file ui.h.
COLOR_ERROR
#define COLOR_ERROR 0xc8a6
Color definitions (RGB565 format).
Color for error messages.
Definition at line 32 of file ui.h.
COLOR_GIRD
#define COLOR_GIRD 0xef9d
Color for grid lines.
Definition at line 33 of file ui.h.
COLOR_LEGEND_BG
#define COLOR_LEGEND_BG 0xef7d
Background color for legends.
Definition at line 36 of file ui.h.
Typedef Documentation
gridInfo_t
typedef struct gridInfo_t gridInfo_t
Structure defining grid layout properties for graphs.
Enumeration Type Documentation
SCREEN_FLAG_BIT_ORDER
enum SCREEN_FLAG_BIT_ORDER
Bit definitions for screen control flags.
Enumerator
SCREEN_RENDER
Flag bit to request screen rendering (Flush).
SCREEN_TURN_ON
Flag bit to turn on the screen.
SCREEN_TURN_OFF
Flag bit to turn off the screen.
SCREEN_FLAG_BIT_ORDER_NUMBER
Definition at line 52 of file ui.h.
{
    SCREEN_RENDER = 0,
    SCREEN_TURN_ON = 0,
    SCREEN_TURN_OFF = 0,
    SCREEN_FLAG_BIT_ORDER_NUMBER,
};
Function Documentation
lcdInit()
void lcdInit ()
Initialize the LCD device and configure pins.
Definition at line 60 of file ui.h.
              {
    __entry("lcdInit()");
    lcd32CreateDevice(&lcd);
    lcd32DataPin_t dataPin = {
        .__0 = LCD32_DB0,   .__1 = LCD32_DB1,   .__2 = LCD32_DB2,   .__3 = LCD32_DB3,
        .__4 = LCD32_DB4,   .__5 = LCD32_DB5,   .__6 = LCD32_DB6,   .__7 = LCD32_DB7,
        .__8 = LCD32_DB8,   .__9 = LCD32_DB9,   .__10 = LCD32_DB10, .__11 = LCD32_DB11,
        .__12 = LCD32_DB12, .__13 = LCD32_DB13, .__14 = LCD32_DB14, .__15 = LCD32_DB15
    };
    lcd32ControlPin_t ctlPin = {
        .r = LCD32_RD,  .w = LCD32_WR,
        .rs= LCD32_RS,  .cs= LCD32_CS,
        .rst=LCD32_RST, .bl= LCD32_BL
    };
    lcd32ConfigDevice(lcd, &dataPin, &ctlPin, LCD32_MAX_ROW, LCD32_MAX_COL);
    lcd32StartUpDevice(lcd);
    // lcd32FillCanvas(lcd, 15);
    // lcd32FlushCanvas(lcd);
    __exit("lcdInit()");
}
References __0, __1, __10, __11, __12, __13, __14, __15, __2, __3, __4, __5, __6, __7, __8, __9, lcd, lcd32ConfigDevice(), lcd32CreateDevice(), lcd32DataPin_t, and lcd32StartUpDevice().
Referenced by systemInit().
lcdShowIntroScreen()
void lcdShowIntroScreen ()
Display the project introduction screen.
Definition at line 83 of file ui.h.
{
    __entry("lcdShowIntroScreen()");
    lcd32FillCanvas(lcd, 0xFFFF); // Black background
    lcd32DrawText(lcd, 40, 5, "DO AN 02", &fontHeading01, 0x0152);
    lcd32DrawText(lcd, 80, 5, "[1] Nguyen Thanh Phu - 22119211", &fontHeading03, 0x2925);
    lcd32DrawText(lcd, 100, 5, "[2] Nguyen Van Quoc  - 22119222", &fontHeading03, 0x2925);
    lcd32FlushCanvas(lcd);
    vTaskDelay(pdMS_TO_TICKS(1000)); // Display for 2 seconds
    __exit("lcdShowIntroScreen()");
}
References lcd, lcd32DrawText(), lcd32FillCanvas(), and lcd32FlushCanvas().
Referenced by systemInit().
screenControlTask()
void screenControlTask (void * pv)
Task to handle screen updates, rendering, and power states based on event flags.
Parameters
pv Task parameter (unused).
Definition at line 268 of file ui.h.
{
    WAIT_SYSTEM_INIT_COMPLETED();
    __entry("screenControlTask()");
    flag_t localScreenFlag;
    while(!IS_SYSTEM_STOPPED){
        PERFORM_IN_CRITICAL(&screenFlagMutex,
            localScreenFlag = screenFlag;
            screenFlag = 0;
        );
        while (__isnot_zero(localScreenFlag)){
            if(__hasFlagBitSet(localScreenFlag, SCREEN_RENDER)){
                __clearFlagBit(localScreenFlag, SCREEN_RENDER);
                lcd32FlushCanvas(lcd);
            }
            if(__hasFlagBitSet(localScreenFlag, SCREEN_TURN_ON)){
                __clearFlagBit(localScreenFlag, SCREEN_TURN_ON);
                lcd32WakeFromSleep(lcd);
            }
            if(__hasFlagBitSet(localScreenFlag, SCREEN_TURN_OFF)){
                __clearFlagBit(localScreenFlag, SCREEN_TURN_OFF);
                lcd32PutToSleep(lcd);
            }
            if(__isnot_zero(localScreenFlag)){
                __sys_err("[screenControlTask] Warning: Unrecognized screenFlag bits: 0x%08x", localScreenFlag);
                localScreenFlag = 0;
            }
        }
        vTaskDelay(0);
    }
    __exit("screenControlTask()");
}
References lcd, lcd32FlushCanvas(), lcd32PutToSleep(), lcd32WakeFromSleep(), SCREEN_RENDER, SCREEN_TURN_OFF, SCREEN_TURN_ON, and screenFlag.
Referenced by systemInit().
Variable Documentation
gridInfoTable
const gridInfo_t gridInfoTable[] static
Initial value:
= {
    {  1, 320, 240, 1, 1 },
    {  2, 160, 120, 2, 2 },
    {  4,  80,  60, 4, 4 },
    {  5,  64,  48, 5, 5 },
    {  8,  40,  30, 8, 8 },
    { 10,  32,  24,10,10 },
    { 16,  20,  15,16,16 },
    { 20,  16,  12,20,20 },
    { 40,   8,   6,40,40 },
    { 80,   4,   3,80,80 }
}
Lookup table for different grid density configurations.
Definition at line 18 of file ui.h.
{
    {  1, 320, 240, 1, 1 },
    {  2, 160, 120, 2, 2 },
    {  4,  80,  60, 4, 4 },
    {  5,  64,  48, 5, 5 },
    {  8,  40,  30, 8, 8 },
    { 10,  32,  24,10,10 },
    { 16,  20,  15,16,16 },
    { 20,  16,  12,20,20 },
    { 40,   8,   6,40,40 },
    { 80,   4,   3,80,80 }
};
lcd
lcd32Dev_t* lcd
Pointer to the global LCD device instance.
Definition at line 43 of file ui.h.
Referenced by lcdInit(), lcdShowIntroScreen(), and screenControlTask().
screenFlag
volatile flag_t screenFlag = SYSTEM_INIT
Global flag for screen state management.
Definition at line 46 of file ui.h.
Referenced by screenControlTask().
screenFlagMutex
portMUX_TYPE screenFlagMutex = portMUX_INITIALIZER_UNLOCKED
Mutex for protecting screenFlag access.
Definition at line 49 of file ui.h.